export interface RepresentativeWord {
  word: string
  phonetic: string
  meaning: string
  highlight: string
}

export type IpaCategory =
  | 'monophthong'
  | 'diphthong'
  | 'plosive'
  | 'fricative'
  | 'affricate'
  | 'nasal_liquid'

export interface IpaSymbolItem {
  id: string
  symbol: string
  name: string
  category: IpaCategory
  categoryLabel: string
  subcategory: string
  isVoiced?: boolean // 针对辅音：true为浊辅音，false为清辅音
  soundFile: string
  articulationTip: string
  commonSpellings: string[]
  words: [
    RepresentativeWord,
    RepresentativeWord,
    RepresentativeWord,
    RepresentativeWord,
    RepresentativeWord,
    RepresentativeWord
  ]
}

export const IPA_SYMBOLS_DATA: IpaSymbolItem[] = [
  // ==========================================
  // 一、单元音 (12个)
  // ==========================================
  {
    id: 'i_long',
    symbol: 'iː',
    name: '长前元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '前元音 · 长元音',
    soundFile: 'i_long',
    articulationTip: '舌尖抵下齿，舌前部尽量向硬腭抬起。嘴角向两侧尽量拉开，呈微笑状，发音饱满持久。',
    commonSpellings: ['ee', 'ea', 'e', 'ie', 'ei'],
    words: [
      { word: 'see', phonetic: '/siː/', meaning: '看见；领会', highlight: 'ee' },
      { word: 'tea', phonetic: '/tiː/', meaning: '茶；茶叶', highlight: 'ea' },
      { word: 'sleep', phonetic: '/sliːp/', meaning: '睡觉；睡眠', highlight: 'ee' },
      { word: 'feel', phonetic: '/fiːl/', meaning: '感觉；触摸', highlight: 'ee' },
      { word: 'deep', phonetic: '/diːp/', meaning: '深的；深厚的', highlight: 'ee' },
      { word: 'keep', phonetic: '/kiːp/', meaning: '保持；保存', highlight: 'ee' },
    ],
  },
  {
    id: 'i_short',
    symbol: 'ɪ',
    name: '短前元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '前元音 · 短元音',
    soundFile: 'i_short',
    articulationTip: '舌尖抵下齿，舌前部向硬腭抬起，牙床开一指宽，双唇放松微开，发音短促有力。',
    commonSpellings: ['i', 'y', 'e'],
    words: [
      { word: 'sit', phonetic: '/sɪt/', meaning: '坐下；就座', highlight: 'i' },
      { word: 'big', phonetic: '/bɪɡ/', meaning: '大的；重大的', highlight: 'i' },
      { word: 'fish', phonetic: '/fɪʃ/', meaning: '鱼；钓鱼', highlight: 'i' },
      { word: 'hit', phonetic: '/hɪt/', meaning: '击打；击中', highlight: 'i' },
      { word: 'pink', phonetic: '/pɪŋk/', meaning: '粉色的；粉红', highlight: 'i' },
      { word: 'win', phonetic: '/wɪn/', meaning: '赢取；获胜', highlight: 'i' },
    ],
  },
  {
    id: 'e',
    symbol: 'e',
    name: '短前元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '前元音 · 短元音',
    soundFile: 'e',
    articulationTip: '舌尖抵下齿，舌前部稍抬高，牙床开一指半，双唇稍扁平，发音干脆自然。',
    commonSpellings: ['e', 'ea'],
    words: [
      { word: 'bed', phonetic: '/bed/', meaning: '床；卧榻', highlight: 'e' },
      { word: 'red', phonetic: '/red/', meaning: '红色的', highlight: 'e' },
      { word: 'pen', phonetic: '/pen/', meaning: '钢笔；圆珠笔', highlight: 'e' },
      { word: 'desk', phonetic: '/desk/', meaning: '书桌；办公桌', highlight: 'e' },
      { word: 'head', phonetic: '/hed/', meaning: '头部；主管', highlight: 'ea' },
      { word: 'leg', phonetic: '/leɡ/', meaning: '腿；支柱', highlight: 'e' },
    ],
  },
  {
    id: 'ae',
    symbol: 'æ',
    name: '短前元音(大口梅花音)',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '前元音 · 短元音',
    soundFile: 'ae',
    articulationTip: '舌尖抵下齿，牙床大开（约两指宽），口腔充分开阔，嘴角向两侧微咧，声带振动。',
    commonSpellings: ['a'],
    words: [
      { word: 'cat', phonetic: '/kæt/', meaning: '猫', highlight: 'a' },
      { word: 'bag', phonetic: '/bæɡ/', meaning: '书包；提包', highlight: 'a' },
      { word: 'apple', phonetic: '/ˈæpl/', meaning: '苹果', highlight: 'a' },
      { word: 'hat', phonetic: '/hæt/', meaning: '帽子', highlight: 'a' },
      { word: 'map', phonetic: '/mæp/', meaning: '地图', highlight: 'a' },
      { word: 'black', phonetic: '/blæk/', meaning: '黑色的', highlight: 'a' },
    ],
  },
  {
    id: 'er_long',
    symbol: 'ɜː',
    name: '长中元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '中元音 · 长元音',
    soundFile: 'er_long',
    articulationTip: '舌身放平，舌中部稍抬起，牙床微开，双唇扁平中立，肌肉放松，声带发长音。',
    commonSpellings: ['ir', 'ur', 'er', 'ear', 'or'],
    words: [
      { word: 'bird', phonetic: '/bɜːd/', meaning: '鸟；禽', highlight: 'ir' },
      { word: 'girl', phonetic: '/ɡɜːl/', meaning: '女孩；少女', highlight: 'ir' },
      { word: 'nurse', phonetic: '/nɜːs/', meaning: '护士；照料', highlight: 'ur' },
      { word: 'shirt', phonetic: '/ʃɜːt/', meaning: '衬衫', highlight: 'ir' },
      { word: 'work', phonetic: '/wɜːk/', meaning: '工作；运转', highlight: 'or' },
      { word: 'learn', phonetic: '/lɜːn/', meaning: '学习；获悉', highlight: 'ear' },
    ],
  },
  {
    id: 'schwa',
    symbol: 'ə',
    name: '短中元音(轻央元音)',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '中元音 · 短元音',
    soundFile: 'schwa',
    articulationTip: '最松弛元音。舌身自然平放，嘴唇微张自然放松，声带轻轻振动，短弱迅速。',
    commonSpellings: ['a', 'e', 'o', 'er', 'or'],
    words: [
      { word: 'about', phonetic: '/əˈbaʊt/', meaning: '关于；大约', highlight: 'a' },
      { word: 'banana', phonetic: '/bəˈnɑːnə/', meaning: '香蕉', highlight: 'a' },
      { word: 'doctor', phonetic: '/ˈdɒktə(r)/', meaning: '医生；博士', highlight: 'or' },
      { word: 'teacher', phonetic: '/ˈtiːtʃə(r)/', meaning: '老师；教师', highlight: 'er' },
      { word: 'water', phonetic: '/ˈwɔːtə(r)/', meaning: '水；浇水', highlight: 'er' },
      { word: 'ago', phonetic: '/əˈɡəʊ/', meaning: '以前；以往', highlight: 'a' },
    ],
  },
  {
    id: 'wedge',
    symbol: 'ʌ',
    name: '短后元音(扁唇阿音)',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '后元音 · 短元音',
    soundFile: 'wedge',
    articulationTip: '舌尖离开下齿后缩，舌后部微抬，牙床半开，双唇向两旁平伸成自然扁圆形。',
    commonSpellings: ['u', 'o', 'ou'],
    words: [
      { word: 'cup', phonetic: '/kʌp/', meaning: '杯子；茶杯', highlight: 'u' },
      { word: 'bus', phonetic: '/bʌs/', meaning: '公交车；公共汽车', highlight: 'u' },
      { word: 'sun', phonetic: '/sʌn/', meaning: '太阳；阳光', highlight: 'u' },
      { word: 'run', phonetic: '/rʌn/', meaning: '跑；运转', highlight: 'u' },
      { word: 'duck', phonetic: '/dʌk/', meaning: '鸭子', highlight: 'u' },
      { word: 'nut', phonetic: '/nʌt/', meaning: '坚果；螺母', highlight: 'u' },
    ],
  },
  {
    id: 'a_long',
    symbol: 'ɑː',
    name: '长后元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '后元音 · 长元音',
    soundFile: 'a_long',
    articulationTip: '口腔充分张开，舌身平放后缩，舌尖离开下齿，双唇呈自然圆形，发出深长饱满的音。',
    commonSpellings: ['ar', 'a'],
    words: [
      { word: 'car', phonetic: '/kɑː(r)/', meaning: '汽车；轿车', highlight: 'ar' },
      { word: 'park', phonetic: '/pɑːk/', meaning: '公园；停放', highlight: 'ar' },
      { word: 'star', phonetic: '/stɑː(r)/', meaning: '星星；恒星', highlight: 'ar' },
      { word: 'dark', phonetic: '/dɑːk/', meaning: '黑暗的；深色的', highlight: 'ar' },
      { word: 'farm', phonetic: '/fɑːm/', meaning: '农场；农庄', highlight: 'ar' },
      { word: 'father', phonetic: '/ˈfɑːðə(r)/', meaning: '父亲；爸爸', highlight: 'a' },
    ],
  },
  {
    id: 'o_short',
    symbol: 'ɒ',
    name: '短后元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '后元音 · 短元音',
    soundFile: 'o_short',
    articulationTip: '口腔大开，舌身降低后缩，双唇收圆并略向前突出，短促发音。',
    commonSpellings: ['o', 'a'],
    words: [
      { word: 'hot', phonetic: '/hɒt/', meaning: '热的；辣的', highlight: 'o' },
      { word: 'dog', phonetic: '/dɒɡ/', meaning: '狗；猎犬', highlight: 'o' },
      { word: 'box', phonetic: '/bɒks/', meaning: '盒子；箱子', highlight: 'o' },
      { word: 'stop', phonetic: '/stɒp/', meaning: '停止；阻止', highlight: 'o' },
      { word: 'clock', phonetic: '/klɒk/', meaning: '时钟；座钟', highlight: 'o' },
      { word: 'shop', phonetic: '/ʃɒp/', meaning: '商店；购物', highlight: 'o' },
    ],
  },
  {
    id: 'o_long',
    symbol: 'ɔː',
    name: '长后元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '后元音 · 长元音',
    soundFile: 'o_long',
    articulationTip: '舌后部抬起，双唇收得更圆更小，用力向前突出，发音深长洪亮。',
    commonSpellings: ['or', 'al', 'oor', 'our', 'au', 'aw'],
    words: [
      { word: 'door', phonetic: '/dɔː(r)/', meaning: '门；通道', highlight: 'oor' },
      { word: 'horse', phonetic: '/hɔːs/', meaning: '马', highlight: 'or' },
      { word: 'ball', phonetic: '/bɔːl/', meaning: '球；舞会', highlight: 'all' },
      { word: 'fork', phonetic: '/fɔːk/', meaning: '餐叉；叉子', highlight: 'or' },
      { word: 'warm', phonetic: '/wɔːm/', meaning: '温暖的', highlight: 'ar' },
      { word: 'tall', phonetic: '/tɔːl/', meaning: '高的；高大的', highlight: 'all' },
    ],
  },
  {
    id: 'u_short',
    symbol: 'ʊ',
    name: '短后元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '后元音 · 短元音',
    soundFile: 'u_short',
    articulationTip: '舌后部向软腭抬起，舌身松弛后缩，双唇微收圆略向前伸，短促发声。',
    commonSpellings: ['oo', 'u', 'o'],
    words: [
      { word: 'book', phonetic: '/bʊk/', meaning: '书本；书籍', highlight: 'oo' },
      { word: 'look', phonetic: '/lʊk/', meaning: '看；注视', highlight: 'oo' },
      { word: 'good', phonetic: '/ɡʊd/', meaning: '好的；优秀的', highlight: 'oo' },
      { word: 'foot', phonetic: '/fʊt/', meaning: '脚；英尺', highlight: 'oo' },
      { word: 'cook', phonetic: '/kʊk/', meaning: '烹饪；厨师', highlight: 'oo' },
      { word: 'wood', phonetic: '/wʊd/', meaning: '木头；树林', highlight: 'oo' },
    ],
  },
  {
    id: 'u_long',
    symbol: 'uː',
    name: '长后元音',
    category: 'monophthong',
    categoryLabel: '单元音',
    subcategory: '后元音 · 长元音',
    soundFile: 'u_long',
    articulationTip: '舌后部尽量向上抬起，双唇收得很圆很小，用力向前突出成小孔状，发出长音。',
    commonSpellings: ['oo', 'u', 'ue', 'ui'],
    words: [
      { word: 'moon', phonetic: '/muːn/', meaning: '月亮；月球', highlight: 'oo' },
      { word: 'food', phonetic: '/fuːd/', meaning: '食物；粮食', highlight: 'oo' },
      { word: 'blue', phonetic: '/bluː/', meaning: '蓝色的', highlight: 'ue' },
      { word: 'ruler', phonetic: '/ˈruːlə(r)/', meaning: '尺子；统治者', highlight: 'u' },
      { word: 'fruit', phonetic: '/fruːt/', meaning: '水果；成果', highlight: 'ui' },
      { word: 'cool', phonetic: '/kuːl/', meaning: '凉爽的；酷的', highlight: 'oo' },
    ],
  },

  // ==========================================
  // 二、双元音 (8个)
  // ==========================================
  {
    id: 'ei',
    symbol: 'eɪ',
    name: '合口双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '合口双元音',
    soundFile: 'ei',
    articulationTip: '由前元音 /e/ 滑向 /ɪ/。前重后轻，前长后短，双唇随滑音由半开收拢变窄。',
    commonSpellings: ['a', 'ay', 'ai', 'ey', 'eigh'],
    words: [
      { word: 'face', phonetic: '/feɪs/', meaning: '脸庞；面对', highlight: 'a' },
      { word: 'name', phonetic: '/neɪm/', meaning: '名字；名称', highlight: 'a' },
      { word: 'play', phonetic: '/pleɪ/', meaning: '玩耍；播放', highlight: 'ay' },
      { word: 'rain', phonetic: '/reɪn/', meaning: '雨；下雨', highlight: 'ai' },
      { word: 'make', phonetic: '/meɪk/', meaning: '制造；制作', highlight: 'a' },
      { word: 'day', phonetic: '/deɪ/', meaning: '白天；一天', highlight: 'ay' },
    ],
  },
  {
    id: 'ai',
    symbol: 'aɪ',
    name: '合口双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '合口双元音',
    soundFile: 'ai',
    articulationTip: '由开元音 /a/ 滑向 /ɪ/。起音时口腔大开，滑动过程中下颌合拢，口形迅速变扁。',
    commonSpellings: ['i', 'y', 'ie', 'igh'],
    words: [
      { word: 'bike', phonetic: '/baɪk/', meaning: '自行车', highlight: 'i' },
      { word: 'time', phonetic: '/taɪm/', meaning: '时间；时代', highlight: 'i' },
      { word: 'fly', phonetic: '/flaɪ/', meaning: '飞翔；苍蝇', highlight: 'y' },
      { word: 'night', phonetic: '/naɪt/', meaning: '夜晚；夜间', highlight: 'igh' },
      { word: 'like', phonetic: '/laɪk/', meaning: '喜欢；如同', highlight: 'i' },
      { word: 'sky', phonetic: '/skaɪ/', meaning: '天空', highlight: 'y' },
    ],
  },
  {
    id: 'oi',
    symbol: 'ɔɪ',
    name: '合口双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '合口双元音',
    soundFile: 'oi',
    articulationTip: '由后元音 /ɔː/ 滑向 /ɪ/。起音双唇收圆微噘，然后迅速放松扁平滑向 /ɪ/。',
    commonSpellings: ['oi', 'oy'],
    words: [
      { word: 'boy', phonetic: '/bɔɪ/', meaning: '男孩；少年', highlight: 'oy' },
      { word: 'toy', phonetic: '/tɔɪ/', meaning: '玩具', highlight: 'oy' },
      { word: 'coin', phonetic: '/kɔɪn/', meaning: '硬币；金钱', highlight: 'oi' },
      { word: 'point', phonetic: '/pɔɪnt/', meaning: '点；指出', highlight: 'oi' },
      { word: 'voice', phonetic: '/vɔɪs/', meaning: '声音；嗓音', highlight: 'oi' },
      { word: 'oil', phonetic: '/ɔɪl/', meaning: '油；石油', highlight: 'oi' },
    ],
  },
  {
    id: 'au',
    symbol: 'aʊ',
    name: '合口双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '合口双元音',
    soundFile: 'au',
    articulationTip: '由 /a/ 滑向 /ʊ/。口形由大开逐渐收圆变小，舌后部相应抬起，如“啊-呜”。',
    commonSpellings: ['ou', 'ow'],
    words: [
      { word: 'now', phonetic: '/naʊ/', meaning: '现在；目前', highlight: 'ow' },
      { word: 'cow', phonetic: '/kaʊ/', meaning: '奶牛；母牛', highlight: 'ow' },
      { word: 'house', phonetic: '/haʊs/', meaning: '房屋；住宅', highlight: 'ou' },
      { word: 'mouth', phonetic: '/maʊθ/', meaning: '嘴巴；口腔', highlight: 'ou' },
      { word: 'shout', phonetic: '/ʃaʊt/', meaning: '呼喊；大叫', highlight: 'ou' },
      { word: 'out', phonetic: '/aʊt/', meaning: '在外面；出来', highlight: 'ou' },
    ],
  },
  {
    id: 'ou_uk',
    symbol: 'əʊ',
    name: '合口双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '合口双元音',
    soundFile: 'ou_uk',
    articulationTip: '英音由央元音 /ə/ 滑向 /ʊ/（美音常记作 /oʊ/）。双唇由半开自然过渡到微圆向前突出。',
    commonSpellings: ['o', 'oa', 'ow'],
    words: [
      { word: 'go', phonetic: '/ɡəʊ/', meaning: '去；行走', highlight: 'o' },
      { word: 'no', phonetic: '/nəʊ/', meaning: '不；没有', highlight: 'o' },
      { word: 'home', phonetic: '/həʊm/', meaning: '家；家庭', highlight: 'o' },
      { word: 'boat', phonetic: '/bəʊt/', meaning: '小船；小艇', highlight: 'oa' },
      { word: 'nose', phonetic: '/nəʊz/', meaning: '鼻子', highlight: 'o' },
      { word: 'snow', phonetic: '/snəʊ/', meaning: '雪；下雪', highlight: 'ow' },
    ],
  },
  {
    id: 'ia',
    symbol: 'ɪə',
    name: '集中双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '集中双元音',
    soundFile: 'ia',
    articulationTip: '由前元音 /ɪ/ 向央元音 /ə/ 滑动。舌位由前向上逐渐降至中位，双唇始终保持中立放松。',
    commonSpellings: ['ear', 'eer', 'ere'],
    words: [
      { word: 'ear', phonetic: '/ɪə(r)/', meaning: '耳朵；听觉', highlight: 'ear' },
      { word: 'hear', phonetic: '/hɪə(r)/', meaning: '听见；倾听', highlight: 'ear' },
      { word: 'near', phonetic: '/nɪə(r)/', meaning: '附近的；靠近', highlight: 'ear' },
      { word: 'deer', phonetic: '/dɪə(r)/', meaning: '鹿', highlight: 'eer' },
      { word: 'tear', phonetic: '/tɪə(r)/', meaning: '眼泪；泪水', highlight: 'ear' },
      { word: 'clear', phonetic: '/klɪə(r)/', meaning: '清楚的；清澈的', highlight: 'ear' },
    ],
  },
  {
    id: 'ea',
    symbol: 'eə',
    name: '集中双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '集中双元音',
    soundFile: 'ea',
    articulationTip: '由前半开元音 /e/ 滑向央元音 /ə/。嘴唇微开，牙床开一指半滑向放松闭合。',
    commonSpellings: ['air', 'are', 'ear', 'ere'],
    words: [
      { word: 'air', phonetic: '/eə(r)/', meaning: '空气；大气', highlight: 'air' },
      { word: 'hair', phonetic: '/heə(r)/', meaning: '头发；毛发', highlight: 'air' },
      { word: 'chair', phonetic: '/tʃeə(r)/', meaning: '椅子；讲座', highlight: 'air' },
      { word: 'care', phonetic: '/keə(r)/', meaning: '关心；介意', highlight: 'are' },
      { word: 'bear', phonetic: '/beə(r)/', meaning: '熊；承受', highlight: 'ear' },
      { word: 'pear', phonetic: '/peə(r)/', meaning: '梨；梨树', highlight: 'ear' },
    ],
  },
  {
    id: 'ua',
    symbol: 'ʊə',
    name: '集中双元音',
    category: 'diphthong',
    categoryLabel: '双元音',
    subcategory: '集中双元音',
    soundFile: 'ua',
    articulationTip: '由后圆唇元音 /ʊ/ 滑向央元音 /ə/。双唇由略圆向半开自然放松过渡。',
    commonSpellings: ['oor', 'our', 'ure'],
    words: [
      { word: 'tour', phonetic: '/tʊə(r)/', meaning: '旅游；观光', highlight: 'our' },
      { word: 'poor', phonetic: '/pʊə(r)/', meaning: '贫穷的；可怜的', highlight: 'oor' },
      { word: 'pure', phonetic: '/pjʊə(r)/', meaning: '纯洁的；纯正的', highlight: 'ure' },
      { word: 'sure', phonetic: '/ʃʊə(r)/', meaning: '确定的；当然', highlight: 'ure' },
      { word: 'cure', phonetic: '/kjʊə(r)/', meaning: '治愈；疗法', highlight: 'ure' },
      { word: 'mature', phonetic: '/məˈtʃʊə(r)/', meaning: '成熟的', highlight: 'ure' },
    ],
  },

  // ==========================================
  // 三、清辅音 (11个)
  // ==========================================
  {
    id: 'p',
    symbol: 'p',
    name: '双唇爆破清辅音',
    category: 'plosive',
    categoryLabel: '辅音 · 爆破音',
    subcategory: '爆破音',
    isVoiced: false,
    soundFile: 'p',
    articulationTip: '双唇紧闭阻断气流，然后突然分开让气流爆破而出。声带不振动，纯气流音。',
    commonSpellings: ['p', 'pp'],
    words: [
      { word: 'pen', phonetic: '/pen/', meaning: '钢笔', highlight: 'p' },
      { word: 'pig', phonetic: '/pɪɡ/', meaning: '猪', highlight: 'p' },
      { word: 'cap', phonetic: '/kæp/', meaning: '便帽；盖子', highlight: 'p' },
      { word: 'map', phonetic: '/mæp/', meaning: '地图', highlight: 'p' },
      { word: 'stop', phonetic: '/stɒp/', meaning: '停止', highlight: 'p' },
      { word: 'cup', phonetic: '/kʌp/', meaning: '杯子', highlight: 'p' },
    ],
  },
  {
    id: 't',
    symbol: 't',
    name: '齿龈爆破清辅音',
    category: 'plosive',
    categoryLabel: '辅音 · 爆破音',
    subcategory: '爆破音',
    isVoiced: false,
    soundFile: 't',
    articulationTip: '舌尖紧贴上齿龈阻挡气流，随后舌尖突然放开，气流冲出口腔。声带不振动。',
    commonSpellings: ['t', 'tt'],
    words: [
      { word: 'tea', phonetic: '/tiː/', meaning: '茶', highlight: 't' },
      { word: 'ten', phonetic: '/ten/', meaning: '十', highlight: 't' },
      { word: 'cat', phonetic: '/kæt/', meaning: '猫', highlight: 't' },
      { word: 'hat', phonetic: '/hæt/', meaning: '帽子', highlight: 't' },
      { word: 'sit', phonetic: '/sɪt/', meaning: '坐', highlight: 't' },
      { word: 'wait', phonetic: '/weɪt/', meaning: '等待', highlight: 't' },
    ],
  },
  {
    id: 'k',
    symbol: 'k',
    name: '软腭爆破清辅音',
    category: 'plosive',
    categoryLabel: '辅音 · 爆破音',
    subcategory: '爆破音',
    isVoiced: false,
    soundFile: 'k',
    articulationTip: '舌后部紧贴软腭阻挡气流，随后突然分开，气流冲出。声带不振动。',
    commonSpellings: ['k', 'c', 'ck', 'ch'],
    words: [
      { word: 'cat', phonetic: '/kæt/', meaning: '猫', highlight: 'c' },
      { word: 'kite', phonetic: '/kaɪt/', meaning: '风筝', highlight: 'k' },
      { word: 'book', phonetic: '/bʊk/', meaning: '书', highlight: 'k' },
      { word: 'cake', phonetic: '/keɪk/', meaning: '蛋糕', highlight: 'c' },
      { word: 'milk', phonetic: '/mɪlk/', meaning: '牛奶', highlight: 'k' },
      { word: 'duck', phonetic: '/dʌk/', meaning: '鸭子', highlight: 'ck' },
    ],
  },
  {
    id: 'f',
    symbol: 'f',
    name: '唇齿摩擦清辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: false,
    soundFile: 'f',
    articulationTip: '上齿轻触下唇内侧，气流从唇齿缝隙间摩擦挤出。声带不振动。',
    commonSpellings: ['f', 'ff', 'ph'],
    words: [
      { word: 'fish', phonetic: '/fɪʃ/', meaning: '鱼', highlight: 'f' },
      { word: 'fat', phonetic: '/fæt/', meaning: '肥胖的', highlight: 'f' },
      { word: 'leaf', phonetic: '/liːf/', meaning: '叶子', highlight: 'f' },
      { word: 'phone', phonetic: '/fəʊn/', meaning: '电话', highlight: 'ph' },
      { word: 'coffee', phonetic: '/ˈkɒfi/', meaning: '咖啡', highlight: 'ff' },
      { word: 'roof', phonetic: '/ruːf/', meaning: '屋顶', highlight: 'f' },
    ],
  },
  {
    id: 'th_voiceless',
    symbol: 'θ',
    name: '齿间摩擦清辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: false,
    soundFile: 'th_voiceless',
    articulationTip: '咬舌音。舌尖轻放于上下门齿之间，气流从舌齿缝隙中吹出。声带不振动。',
    commonSpellings: ['th'],
    words: [
      { word: 'thank', phonetic: '/θæŋk/', meaning: '感谢', highlight: 'th' },
      { word: 'think', phonetic: '/θɪŋk/', meaning: '思考；认为', highlight: 'th' },
      { word: 'thin', phonetic: '/θɪn/', meaning: '瘦的；薄的', highlight: 'th' },
      { word: 'math', phonetic: '/mæθ/', meaning: '数学', highlight: 'th' },
      { word: 'mouth', phonetic: '/maʊθ/', meaning: '嘴巴', highlight: 'th' },
      { word: 'tooth', phonetic: '/tuːθ/', meaning: '牙齿', highlight: 'th' },
    ],
  },
  {
    id: 's',
    symbol: 's',
    name: '齿龈摩擦清辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: false,
    soundFile: 's',
    articulationTip: '舌尖靠近上齿龈，留下细狭缝隙，气流通过缝隙发出类似蛇信的“嘶”声。声带不振动。',
    commonSpellings: ['s', 'ss', 'c'],
    words: [
      { word: 'see', phonetic: '/siː/', meaning: '看见', highlight: 's' },
      { word: 'sun', phonetic: '/sʌn/', meaning: '太阳', highlight: 's' },
      { word: 'bus', phonetic: '/bʌs/', meaning: '公交车', highlight: 's' },
      { word: 'miss', phonetic: '/mɪs/', meaning: '思念；错过', highlight: 'ss' },
      { word: 'sing', phonetic: '/sɪŋ/', meaning: '唱歌', highlight: 's' },
      { word: 'sit', phonetic: '/sɪt/', meaning: '坐', highlight: 's' },
    ],
  },
  {
    id: 'sh',
    symbol: 'ʃ',
    name: '舌端齿龈摩擦清辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: false,
    soundFile: 'sh',
    articulationTip: '双唇略向前突出微呈喇叭状，舌尖抬向上齿龈后部，形成通道，气流摩擦而出。如嘘声“嘘”。',
    commonSpellings: ['sh', 'ti', 'ss', 'ch'],
    words: [
      { word: 'ship', phonetic: '/ʃɪp/', meaning: '轮船', highlight: 'sh' },
      { word: 'fish', phonetic: '/fɪʃ/', meaning: '鱼', highlight: 'sh' },
      { word: 'shop', phonetic: '/ʃɒp/', meaning: '商店', highlight: 'sh' },
      { word: 'wash', phonetic: '/wɒʃ/', meaning: '清洗', highlight: 'sh' },
      { word: 'brush', phonetic: '/brʌʃ/', meaning: '刷子；刷洗', highlight: 'sh' },
      { word: 'sheep', phonetic: '/ʃiːp/', meaning: '绵羊', highlight: 'sh' },
    ],
  },
  {
    id: 'h',
    symbol: 'h',
    name: '声门摩擦清辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: false,
    soundFile: 'h',
    articulationTip: '口形随随后的元音自然张开，气流不受阻碍地从声门摩擦而出，类似哈气。声带不振动。',
    commonSpellings: ['h', 'wh'],
    words: [
      { word: 'hat', phonetic: '/hæt/', meaning: '帽子', highlight: 'h' },
      { word: 'hot', phonetic: '/hɒt/', meaning: '热的', highlight: 'h' },
      { word: 'hen', phonetic: '/hen/', meaning: '母鸡', highlight: 'h' },
      { word: 'hand', phonetic: '/hænd/', meaning: '手', highlight: 'h' },
      { word: 'house', phonetic: '/haʊs/', meaning: '房子', highlight: 'h' },
      { word: 'head', phonetic: '/hed/', meaning: '头', highlight: 'h' },
    ],
  },
  {
    id: 'ch',
    symbol: 'tʃ',
    name: '舌端齿龈破擦清辅音',
    category: 'affricate',
    categoryLabel: '辅音 · 破擦音',
    subcategory: '破擦音',
    isVoiced: false,
    soundFile: 'ch',
    articulationTip: '舌尖先紧贴上齿龈后部阻断气流，随后慢慢放开，气流摩擦冲出。类似汉字“吃”。声带不振动。',
    commonSpellings: ['ch', 'tch'],
    words: [
      { word: 'chair', phonetic: '/tʃeə(r)/', meaning: '椅子', highlight: 'ch' },
      { word: 'chin', phonetic: '/tʃɪn/', meaning: '下巴', highlight: 'ch' },
      { word: 'catch', phonetic: '/kætʃ/', meaning: '抓住', highlight: 'tch' },
      { word: 'watch', phonetic: '/wɒtʃ/', meaning: '手表；观看', highlight: 'tch' },
      { word: 'peach', phonetic: '/piːtʃ/', meaning: '桃子', highlight: 'ch' },
      { word: 'lunch', phonetic: '/lʌntʃ/', meaning: '午餐', highlight: 'ch' },
    ],
  },
  {
    id: 'tr',
    symbol: 'tr',
    name: '齿龈后部破擦清辅音',
    category: 'affricate',
    categoryLabel: '辅音 · 破擦音',
    subcategory: '破擦音',
    isVoiced: false,
    soundFile: 'tr',
    articulationTip: '双唇收圆向前微突，舌尖抵上齿龈后部，阻挡气流后突然放开发出摩擦音。类似“戳”。',
    commonSpellings: ['tr'],
    words: [
      { word: 'tree', phonetic: '/triː/', meaning: '树木', highlight: 'tr' },
      { word: 'try', phonetic: '/traɪ/', meaning: '尝试；努力', highlight: 'tr' },
      { word: 'train', phonetic: '/treɪn/', meaning: '火车；训练', highlight: 'tr' },
      { word: 'truck', phonetic: '/trʌk/', meaning: '卡车', highlight: 'tr' },
      { word: 'travel', phonetic: '/ˈtrævl/', meaning: '旅行', highlight: 'tr' },
      { word: 'trip', phonetic: '/trɪp/', meaning: '旅程', highlight: 'tr' },
    ],
  },
  {
    id: 'ts',
    symbol: 'ts',
    name: '舌尖齿龈破擦清辅音',
    category: 'affricate',
    categoryLabel: '辅音 · 破擦音',
    subcategory: '破擦音',
    isVoiced: false,
    soundFile: 'ts',
    articulationTip: '舌尖贴住上齿龈阻挡气流，气流冲破阻碍由缝隙挤出。类似汉字“次”。声带不振动。',
    commonSpellings: ['ts', 'tes'],
    words: [
      { word: 'cats', phonetic: '/kæts/', meaning: '猫(复数)', highlight: 'ts' },
      { word: 'hats', phonetic: '/hæts/', meaning: '帽子(复数)', highlight: 'ts' },
      { word: 'sits', phonetic: '/sɪts/', meaning: '坐(三单)', highlight: 'ts' },
      { word: 'coats', phonetic: '/kəʊts/', meaning: '外套(复数)', highlight: 'ts' },
      { word: 'boats', phonetic: '/bəʊts/', meaning: '小船(复数)', highlight: 'ts' },
      { word: 'sweets', phonetic: '/swiːts/', meaning: '糖果(复数)', highlight: 'ts' },
    ],
  },

  // ==========================================
  // 四、浊辅音 (17个)
  // ==========================================
  {
    id: 'b',
    symbol: 'b',
    name: '双唇爆破浊辅音',
    category: 'plosive',
    categoryLabel: '辅音 · 爆破音',
    subcategory: '爆破音',
    isVoiced: true,
    soundFile: 'b',
    articulationTip: '双唇紧闭阻断气流，然后突然分开爆发成音。发音瞬间声带强烈振动。',
    commonSpellings: ['b', 'bb'],
    words: [
      { word: 'book', phonetic: '/bʊk/', meaning: '书本', highlight: 'b' },
      { word: 'bag', phonetic: '/bæɡ/', meaning: '书包', highlight: 'b' },
      { word: 'bed', phonetic: '/bed/', meaning: '床', highlight: 'b' },
      { word: 'boy', phonetic: '/bɔɪ/', meaning: '男孩', highlight: 'b' },
      { word: 'club', phonetic: '/klʌb/', meaning: '俱乐部', highlight: 'b' },
      { word: 'rob', phonetic: '/rɒb/', meaning: '抢劫；掠夺', highlight: 'b' },
    ],
  },
  {
    id: 'd',
    symbol: 'd',
    name: '齿龈爆破浊辅音',
    category: 'plosive',
    categoryLabel: '辅音 · 爆破音',
    subcategory: '爆破音',
    isVoiced: true,
    soundFile: 'd',
    articulationTip: '舌尖抵上齿龈阻挡气流，然后突然弹开放开气流。发音时声带剧烈振动。',
    commonSpellings: ['d', 'dd'],
    words: [
      { word: 'dog', phonetic: '/dɒɡ/', meaning: '狗', highlight: 'd' },
      { word: 'door', phonetic: '/dɔː(r)/', meaning: '门', highlight: 'd' },
      { word: 'red', phonetic: '/red/', meaning: '红色的', highlight: 'd' },
      { word: 'bed', phonetic: '/bed/', meaning: '床', highlight: 'd' },
      { word: 'hand', phonetic: '/hænd/', meaning: '手', highlight: 'd' },
      { word: 'kid', phonetic: '/kɪd/', meaning: '孩子', highlight: 'd' },
    ],
  },
  {
    id: 'g',
    symbol: 'ɡ',
    name: '软腭爆破浊辅音',
    category: 'plosive',
    categoryLabel: '辅音 · 爆破音',
    subcategory: '爆破音',
    isVoiced: true,
    soundFile: 'g',
    articulationTip: '舌后部隆起贴紧软腭形成阻碍，随后迅速分离爆破，声带同时振动。',
    commonSpellings: ['g', 'gg'],
    words: [
      { word: 'girl', phonetic: '/ɡɜːl/', meaning: '女孩', highlight: 'g' },
      { word: 'get', phonetic: '/ɡet/', meaning: '得到；到达', highlight: 'g' },
      { word: 'big', phonetic: '/bɪɡ/', meaning: '大的', highlight: 'g' },
      { word: 'bag', phonetic: '/bæɡ/', meaning: '包', highlight: 'g' },
      { word: 'pig', phonetic: '/pɪɡ/', meaning: '猪', highlight: 'g' },
      { word: 'egg', phonetic: '/eɡ/', meaning: '鸡蛋', highlight: 'gg' },
    ],
  },
  {
    id: 'v',
    symbol: 'v',
    name: '唇齿摩擦浊辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: true,
    soundFile: 'v',
    articulationTip: '上门齿紧触下唇内缘，气流从唇齿缝隙挤出，声带剧烈振动发声。',
    commonSpellings: ['v', 've'],
    words: [
      { word: 'vest', phonetic: '/vest/', meaning: '背心；汗衫', highlight: 'v' },
      { word: 'voice', phonetic: '/vɔɪs/', meaning: '声音；嗓音', highlight: 'v' },
      { word: 'live', phonetic: '/lɪv/', meaning: '生活；居住', highlight: 'v' },
      { word: 'have', phonetic: '/hæv/', meaning: '拥有', highlight: 'v' },
      { word: 'five', phonetic: '/faɪv/', meaning: '五', highlight: 'v' },
      { word: 'give', phonetic: '/ɡɪv/', meaning: '给予；赠送', highlight: 'v' },
    ],
  },
  {
    id: 'th_voiced',
    symbol: 'ð',
    name: '齿间摩擦浊辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: true,
    soundFile: 'th_voiced',
    articulationTip: '咬舌音。舌尖轻放上下齿间，气流通过狭缝逸出，声带必须明显振动。',
    commonSpellings: ['th'],
    words: [
      { word: 'this', phonetic: '/ðɪs/', meaning: '这个', highlight: 'th' },
      { word: 'that', phonetic: '/ðæt/', meaning: '那个', highlight: 'th' },
      { word: 'mother', phonetic: '/ˈmʌðə(r)/', meaning: '母亲；妈妈', highlight: 'th' },
      { word: 'father', phonetic: '/ˈfɑːðə(r)/', meaning: '父亲；爸爸', highlight: 'th' },
      { word: 'brother', phonetic: '/ˈbrʌðə(r)/', meaning: '兄弟', highlight: 'th' },
      { word: 'with', phonetic: '/wɪð/', meaning: '和；随着', highlight: 'th' },
    ],
  },
  {
    id: 'z',
    symbol: 'z',
    name: '齿龈摩擦浊辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: true,
    soundFile: 'z',
    articulationTip: '舌尖接近上齿龈，形成窄缝，气流在缝隙摩擦冲出，同时声带剧烈振动发出嗡嗡声。',
    commonSpellings: ['z', 's', 'se'],
    words: [
      { word: 'zoo', phonetic: '/zuː/', meaning: '动物园', highlight: 'z' },
      { word: 'zebra', phonetic: '/ˈzebrə/', meaning: '斑马', highlight: 'z' },
      { word: 'zero', phonetic: '/ˈzɪərəʊ/', meaning: '零', highlight: 'z' },
      { word: 'rose', phonetic: '/rəʊz/', meaning: '玫瑰；蔷薇', highlight: 's' },
      { word: 'nose', phonetic: '/nəʊz/', meaning: '鼻子', highlight: 's' },
      { word: 'size', phonetic: '/saɪz/', meaning: '尺码；大小', highlight: 'z' },
    ],
  },
  {
    id: 'zh',
    symbol: 'ʒ',
    name: '舌端齿龈摩擦浊辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音',
    subcategory: '摩擦音',
    isVoiced: true,
    soundFile: 'zh',
    articulationTip: '双唇略噘突出微圆，舌端靠近硬腭前部，气流冲出缝隙摩擦，声带振动。类似汉字“日”。',
    commonSpellings: ['s', 'si', 'ge'],
    words: [
      { word: 'measure', phonetic: '/ˈmeʒə(r)/', meaning: '测量；措施', highlight: 's' },
      { word: 'leisure', phonetic: '/ˈleʒə(r)/', meaning: '休闲；闲暇', highlight: 's' },
      { word: 'pleasure', phonetic: '/ˈpleʒə(r)/', meaning: '愉快；荣幸', highlight: 's' },
      { word: 'vision', phonetic: '/ˈvɪʒn/', meaning: '视觉；远见', highlight: 'si' },
      { word: 'usual', phonetic: '/ˈjuːʒuəl/', meaning: '通常的；惯常的', highlight: 's' },
      { word: 'beige', phonetic: '/beɪʒ/', meaning: '米色的', highlight: 'ge' },
    ],
  },
  {
    id: 'r',
    symbol: 'r',
    name: '后齿龈无擦通音/浊辅音',
    category: 'fricative',
    categoryLabel: '辅音 · 摩擦音/通音',
    subcategory: '摩擦音',
    isVoiced: true,
    soundFile: 'r',
    articulationTip: '舌尖向上齿龈后部卷起，舌侧贴上齿两侧，气流从舌尖上方溢出，声带振动。',
    commonSpellings: ['r', 'rr', 'wr'],
    words: [
      { word: 'red', phonetic: '/red/', meaning: '红色的', highlight: 'r' },
      { word: 'run', phonetic: '/rʌn/', meaning: '跑；奔跑', highlight: 'r' },
      { word: 'read', phonetic: '/riːd/', meaning: '阅读；看懂', highlight: 'r' },
      { word: 'rain', phonetic: '/reɪn/', meaning: '下雨；雨水', highlight: 'r' },
      { word: 'rose', phonetic: '/rəʊz/', meaning: '玫瑰', highlight: 'r' },
      { word: 'rabbit', phonetic: '/ˈræbɪt/', meaning: '兔子', highlight: 'r' },
    ],
  },
  {
    id: 'dj',
    symbol: 'dʒ',
    name: '舌端齿龈破擦浊辅音',
    category: 'affricate',
    categoryLabel: '辅音 · 破擦音',
    subcategory: '破擦音',
    isVoiced: true,
    soundFile: 'dj',
    articulationTip: '舌尖抵上齿龈后部阻挡气流，随后慢慢滑开放出摩擦音，声带强烈振动。类似汉字“芝”。',
    commonSpellings: ['j', 'g', 'dge'],
    words: [
      { word: 'job', phonetic: '/dʒɒb/', meaning: '工作；职业', highlight: 'j' },
      { word: 'joy', phonetic: '/dʒɔɪ/', meaning: '喜悦；欢乐', highlight: 'j' },
      { word: 'bridge', phonetic: '/brɪdʒ/', meaning: '桥梁', highlight: 'dge' },
      { word: 'judge', phonetic: '/dʒʌdʒ/', meaning: '法官；裁判', highlight: 'j' },
      { word: 'age', phonetic: '/eɪdʒ/', meaning: '年龄；时代', highlight: 'ge' },
      { word: 'page', phonetic: '/peɪdʒ/', meaning: '页面；页码', highlight: 'ge' },
    ],
  },
  {
    id: 'dr',
    symbol: 'dr',
    name: '齿龈后部破擦浊辅音',
    category: 'affricate',
    categoryLabel: '辅音 · 破擦音',
    subcategory: '破擦音',
    isVoiced: true,
    soundFile: 'dr',
    articulationTip: '双唇收圆向前噘出，舌尖抵上齿龈后部，阻断气流后突然放开，声带振动。类似“桌”。',
    commonSpellings: ['dr'],
    words: [
      { word: 'drive', phonetic: '/draɪv/', meaning: '驾驶；驱使', highlight: 'dr' },
      { word: 'dry', phonetic: '/draɪ/', meaning: '干燥的', highlight: 'dr' },
      { word: 'dream', phonetic: '/driːm/', meaning: '梦想；做梦', highlight: 'dr' },
      { word: 'dress', phonetic: '/dres/', meaning: '连衣裙；穿着', highlight: 'dr' },
      { word: 'draw', phonetic: '/drɔː/', meaning: '画画；拉拽', highlight: 'dr' },
      { word: 'drop', phonetic: '/drɒp/', meaning: '落下；滴水', highlight: 'dr' },
    ],
  },
  {
    id: 'dz',
    symbol: 'dz',
    name: '舌尖齿龈破擦浊辅音',
    category: 'affricate',
    categoryLabel: '辅音 · 破擦音',
    subcategory: '破擦音',
    isVoiced: true,
    soundFile: 'dz',
    articulationTip: '舌尖抵上齿龈阻挡气流，随后稍离开让气流摩擦而出，声带剧烈振动。类似“子”。',
    commonSpellings: ['ds', 'des'],
    words: [
      { word: 'birds', phonetic: '/bɜːdz/', meaning: '鸟类(复数)', highlight: 'ds' },
      { word: 'beds', phonetic: '/bedz/', meaning: '床铺(复数)', highlight: 'ds' },
      { word: 'hands', phonetic: '/hændz/', meaning: '双手(复数)', highlight: 'ds' },
      { word: 'kids', phonetic: '/kɪdz/', meaning: '孩子们(复数)', highlight: 'ds' },
      { word: 'cards', phonetic: '/kɑːdz/', meaning: '卡片(复数)', highlight: 'ds' },
      { word: 'friends', phonetic: '/frendz/', meaning: '朋友们(复数)', highlight: 'ds' },
    ],
  },
  {
    id: 'm',
    symbol: 'm',
    name: '双唇鼻音',
    category: 'nasal_liquid',
    categoryLabel: '辅音 · 鼻音',
    subcategory: '鼻音',
    isVoiced: true,
    soundFile: 'm',
    articulationTip: '双唇闭拢，软腭下垂，气流从鼻腔完全倾泻而出，声带持续振动。',
    commonSpellings: ['m', 'mm'],
    words: [
      { word: 'man', phonetic: '/mæn/', meaning: '男人；成年男性', highlight: 'm' },
      { word: 'milk', phonetic: '/mɪlk/', meaning: '牛奶', highlight: 'm' },
      { word: 'moon', phonetic: '/muːn/', meaning: '月亮', highlight: 'm' },
      { word: 'name', phonetic: '/neɪm/', meaning: '名字', highlight: 'm' },
      { word: 'home', phonetic: '/həʊm/', meaning: '家', highlight: 'm' },
      { word: 'summer', phonetic: '/ˈsʌmə(r)/', meaning: '夏天；夏季', highlight: 'mm' },
    ],
  },
  {
    id: 'n',
    symbol: 'n',
    name: '齿龈鼻音',
    category: 'nasal_liquid',
    categoryLabel: '辅音 · 鼻音',
    subcategory: '鼻音',
    isVoiced: true,
    soundFile: 'n',
    articulationTip: '舌尖贴紧上齿龈形成阻塞，气流由鼻腔透出，声带持续振动。',
    commonSpellings: ['n', 'nn', 'kn'],
    words: [
      { word: 'nose', phonetic: '/nəʊz/', meaning: '鼻子', highlight: 'n' },
      { word: 'name', phonetic: '/neɪm/', meaning: '名字', highlight: 'n' },
      { word: 'ten', phonetic: '/ten/', meaning: '十', highlight: 'n' },
      { word: 'pen', phonetic: '/pen/', meaning: '钢笔', highlight: 'n' },
      { word: 'rain', phonetic: '/reɪn/', meaning: '下雨', highlight: 'n' },
      { word: 'sun', phonetic: '/sʌn/', meaning: '太阳', highlight: 'n' },
    ],
  },
  {
    id: 'ng',
    symbol: 'ŋ',
    name: '软腭鼻音',
    category: 'nasal_liquid',
    categoryLabel: '辅音 · 鼻音',
    subcategory: '鼻音',
    isVoiced: true,
    soundFile: 'ng',
    articulationTip: '舌后部隆起贴紧软腭阻断口腔通道，气流全从鼻腔振动透出，声带振动。',
    commonSpellings: ['ng', 'n'],
    words: [
      { word: 'sing', phonetic: '/sɪŋ/', meaning: '唱歌', highlight: 'ng' },
      { word: 'song', phonetic: '/sɒŋ/', meaning: '歌曲', highlight: 'ng' },
      { word: 'ring', phonetic: '/rɪŋ/', meaning: '戒指；铃声', highlight: 'ng' },
      { word: 'long', phonetic: '/lɒŋ/', meaning: '长的；长久的', highlight: 'ng' },
      { word: 'king', phonetic: '/kɪŋ/', meaning: '国王；君主', highlight: 'ng' },
      { word: 'spring', phonetic: '/sprɪŋ/', meaning: '春天；弹簧', highlight: 'ng' },
    ],
  },
  {
    id: 'l',
    symbol: 'l',
    name: '舌侧音',
    category: 'nasal_liquid',
    categoryLabel: '辅音 · 舌侧音',
    subcategory: '舌侧音',
    isVoiced: true,
    soundFile: 'l',
    articulationTip: '清晰[l]舌尖紧贴上齿龈，气流从舌两旁流出；含蓄[l]舌后部稍抬，发低沉尾音。声带振动。',
    commonSpellings: ['l', 'll'],
    words: [
      { word: 'leg', phonetic: '/leɡ/', meaning: '腿', highlight: 'l' },
      { word: 'love', phonetic: '/lʌv/', meaning: '爱；热爱', highlight: 'l' },
      { word: 'ball', phonetic: '/bɔːl/', meaning: '球', highlight: 'll' },
      { word: 'milk', phonetic: '/mɪlk/', meaning: '牛奶', highlight: 'l' },
      { word: 'leaf', phonetic: '/liːf/', meaning: '树叶', highlight: 'l' },
      { word: 'apple', phonetic: '/ˈæpl/', meaning: '苹果', highlight: 'le' },
    ],
  },
  {
    id: 'w',
    symbol: 'w',
    name: '双唇半元音',
    category: 'nasal_liquid',
    categoryLabel: '辅音 · 半元音',
    subcategory: '半元音',
    isVoiced: true,
    soundFile: 'w',
    articulationTip: '舌后部向软腭高抬，双唇收小收圆向前突出，迅速滑向后面的元音，声带振动。',
    commonSpellings: ['w', 'wh'],
    words: [
      { word: 'water', phonetic: '/ˈwɔːtə(r)/', meaning: '水', highlight: 'w' },
      { word: 'watch', phonetic: '/wɒtʃ/', meaning: '手表；观看', highlight: 'w' },
      { word: 'wet', phonetic: '/wet/', meaning: '湿的；潮湿', highlight: 'w' },
      { word: 'wind', phonetic: '/wɪnd/', meaning: '风', highlight: 'w' },
      { word: 'win', phonetic: '/wɪn/', meaning: '获胜；赢得', highlight: 'w' },
      { word: 'wait', phonetic: '/weɪt/', meaning: '等待', highlight: 'w' },
    ],
  },
  {
    id: 'j',
    symbol: 'j',
    name: '硬腭半元音',
    category: 'nasal_liquid',
    categoryLabel: '辅音 · 半元音',
    subcategory: '半元音',
    isVoiced: true,
    soundFile: 'j',
    articulationTip: '舌前部向硬腭抬高，口形扁平，迅速滑向随后的元音成音，声带强烈振动。类似汉语“耶”。',
    commonSpellings: ['y', 'u'],
    words: [
      { word: 'yes', phonetic: '/jes/', meaning: '是的；对的', highlight: 'y' },
      { word: 'you', phonetic: '/juː/', meaning: '你；你们', highlight: 'y' },
      { word: 'yellow', phonetic: '/ˈjeləʊ/', meaning: '黄色的', highlight: 'y' },
      { word: 'yard', phonetic: '/jɑːd/', meaning: '院子；码', highlight: 'y' },
      { word: 'year', phonetic: '/jɪə(r)/', meaning: '年份；年岁', highlight: 'y' },
      { word: 'young', phonetic: '/jʌŋ/', meaning: '年轻的', highlight: 'y' },
    ],
  },
]
