export type PhonicsCategory = 'vowel-vowel' | 'vowel-consonant' | 'consonant-consonant'

export interface PhonicsExampleWord {
  word: string
  phonetic: string
  meaning: string
  highlight: string
}

export interface PhonicsRuleItem {
  id: string
  pattern: string
  category: PhonicsCategory
  categoryLabel: string
  phonetics: string[]
  ruleDescription: string
  positionTip?: string
  examples: PhonicsExampleWord[]
}

export const PHONICS_COMBOS_DATA: PhonicsRuleItem[] = [
  // ==========================================
  // 一、元元组合 (Vowel Digraphs)
  // ==========================================
  {
    id: 'ai',
    pattern: 'ai',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/eɪ/'],
    ruleDescription: '字母组合 ai 常在重读音节词中发双元音 /eɪ/，发音时由 /e/ 平滑过渡到 /ɪ/。',
    positionTip: '多见于单词中间位置，极少作为词尾。',
    examples: [
      { word: 'rain', phonetic: '/reɪn/', meaning: '雨；下雨', highlight: 'ai' },
      { word: 'train', phonetic: '/treɪn/', meaning: '火车；培训', highlight: 'ai' },
      { word: 'wait', phonetic: '/weɪt/', meaning: '等待', highlight: 'ai' },
      { word: 'paint', phonetic: '/peɪnt/', meaning: '油漆；绘画', highlight: 'ai' },
      { word: 'tail', phonetic: '/teɪl/', meaning: '尾巴', highlight: 'ai' },
      { word: 'brain', phonetic: '/breɪn/', meaning: '大脑；智力', highlight: 'ai' },
    ],
  },
  {
    id: 'ay',
    pattern: 'ay',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/eɪ/'],
    ruleDescription: '字母组合 ay 常位于重读音节的词尾，发双元音 /eɪ/。',
    positionTip: '常见于单词词尾。',
    examples: [
      { word: 'day', phonetic: '/deɪ/', meaning: '白天；日子', highlight: 'ay' },
      { word: 'play', phonetic: '/pleɪ/', meaning: '玩耍；播放', highlight: 'ay' },
      { word: 'say', phonetic: '/seɪ/', meaning: '说；表明', highlight: 'ay' },
      { word: 'stay', phonetic: '/steɪ/', meaning: '停留；保持', highlight: 'ay' },
      { word: 'may', phonetic: '/meɪ/', meaning: '可以；五月', highlight: 'ay' },
      { word: 'way', phonetic: '/weɪ/', meaning: '道路；方式', highlight: 'ay' },
    ],
  },
  {
    id: 'ee',
    pattern: 'ee',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/iː/'],
    ruleDescription: '字母组合 ee 在绝大多数情况下发长元音 /iː/，嘴角向两侧自然拉开呈微笑状。',
    positionTip: '常见于词中或词尾。',
    examples: [
      { word: 'see', phonetic: '/siː/', meaning: '看见；领会', highlight: 'ee' },
      { word: 'tree', phonetic: '/triː/', meaning: '树木', highlight: 'ee' },
      { word: 'meet', phonetic: '/miːt/', meaning: '遇见；相逢', highlight: 'ee' },
      { word: 'sleep', phonetic: '/sliːp/', meaning: '睡觉', highlight: 'ee' },
      { word: 'green', phonetic: '/ɡriːn/', meaning: '绿色的', highlight: 'ee' },
      { word: 'keep', phonetic: '/kiːp/', meaning: '保持；保存', highlight: 'ee' },
    ],
  },
  {
    id: 'ea',
    pattern: 'ea',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/iː/', '/e/'],
    ruleDescription: '字母组合 ea 最常见发长元音 /iː/；有时亦可发短元音 /e/。',
    positionTip: '通常位于词首或词中。',
    examples: [
      { word: 'tea', phonetic: '/tiː/', meaning: '茶；茶叶', highlight: 'ea' },
      { word: 'meat', phonetic: '/miːt/', meaning: '肉类', highlight: 'ea' },
      { word: 'read', phonetic: '/riːd/', meaning: '阅读；朗读', highlight: 'ea' },
      { word: 'bread', phonetic: '/bred/', meaning: '面包(发/e/)', highlight: 'ea' },
      { word: 'head', phonetic: '/hed/', meaning: '头；首领(发/e/)', highlight: 'ea' },
      { word: 'peach', phonetic: '/piːtʃ/', meaning: '桃子', highlight: 'ea' },
    ],
  },
  {
    id: 'oa',
    pattern: 'oa',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/əʊ/'],
    ruleDescription: '字母组合 oa 通常发合口双元音 /əʊ/（美音 /oʊ/），口形由半开滑向微圆。',
    positionTip: '多见于辅音字母之间，构成单音节词。',
    examples: [
      { word: 'boat', phonetic: '/bəʊt/', meaning: '小船；小艇', highlight: 'oa' },
      { word: 'coat', phonetic: '/kəʊt/', meaning: '外套；大衣', highlight: 'oa' },
      { word: 'road', phonetic: '/rəʊd/', meaning: '道路；公路', highlight: 'oa' },
      { word: 'soap', phonetic: '/səʊp/', meaning: '肥皂', highlight: 'oa' },
      { word: 'goat', phonetic: '/ɡəʊt/', meaning: '山羊', highlight: 'oa' },
      { word: 'coal', phonetic: '/kəʊl/', meaning: '煤炭', highlight: 'oa' },
    ],
  },
  {
    id: 'oo_long',
    pattern: 'oo (长音)',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/uː/'],
    ruleDescription: '字母组合 oo 在大多数非 k, d 前的辅音字母前发长元音 /uː/，双唇收得很圆很小向前突出。',
    positionTip: '多见于词中，如在 d, l, m, n, t 等字母前。',
    examples: [
      { word: 'food', phonetic: '/fuːd/', meaning: '食物；伙食', highlight: 'oo' },
      { word: 'moon', phonetic: '/muːn/', meaning: '月亮', highlight: 'oo' },
      { word: 'cool', phonetic: '/kuːl/', meaning: '凉爽的；酷', highlight: 'oo' },
      { word: 'tool', phonetic: '/tuːl/', meaning: '工具；用具', highlight: 'oo' },
      { word: 'room', phonetic: '/ruːm/', meaning: '房间；空间', highlight: 'oo' },
      { word: 'zoo', phonetic: '/zuː/', meaning: '动物园', highlight: 'oo' },
    ],
  },
  {
    id: 'oo_short',
    pattern: 'oo (短音)',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/ʊ/'],
    ruleDescription: '字母组合 oo 在字母 k 前（如 book, look）或特殊词（good, foot, wood）中发短元音 /ʊ/。',
    positionTip: '最常见于字母 k 之前，以及常用基础词汇中。',
    examples: [
      { word: 'book', phonetic: '/bʊk/', meaning: '书本；书籍', highlight: 'oo' },
      { word: 'look', phonetic: '/lʊk/', meaning: '看；瞧', highlight: 'oo' },
      { word: 'good', phonetic: '/ɡʊd/', meaning: '好的；善良的', highlight: 'oo' },
      { word: 'foot', phonetic: '/fʊt/', meaning: '脚；英尺', highlight: 'oo' },
      { word: 'cook', phonetic: '/kʊk/', meaning: '做饭；厨师', highlight: 'oo' },
      { word: 'wood', phonetic: '/wʊd/', meaning: '木头；木材', highlight: 'oo' },
    ],
  },
  {
    id: 'ou',
    pattern: 'ou',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/aʊ/'],
    ruleDescription: '字母组合 ou 普遍发双元音 /aʊ/，口形由大开滑向紧圆。特殊词中也可发 /ʌ/ (如 touch, cousin) 或 /uː/ (soup)。',
    positionTip: '常位于词首或词中。',
    examples: [
      { word: 'house', phonetic: '/haʊs/', meaning: '房子；住宅', highlight: 'ou' },
      { word: 'out', phonetic: '/aʊt/', meaning: '在外面；离开', highlight: 'ou' },
      { word: 'loud', phonetic: '/laʊd/', meaning: '大声的；响亮的', highlight: 'ou' },
      { word: 'mouth', phonetic: '/maʊθ/', meaning: '嘴巴', highlight: 'ou' },
      { word: 'cloud', phonetic: '/klaʊd/', meaning: '云朵；阴云', highlight: 'ou' },
      { word: 'shout', phonetic: '/ʃaʊt/', meaning: '大声呼喊', highlight: 'ou' },
    ],
  },
  {
    id: 'ow',
    pattern: 'ow',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/aʊ/', '/əʊ/'],
    ruleDescription: '字母组合 ow 可发双元音 /aʊ/（如 cow, now）或双元音 /əʊ/（如 snow, bowl）。',
    positionTip: '常位于词中或词尾。',
    examples: [
      { word: 'cow', phonetic: '/kaʊ/', meaning: '奶牛；母牛', highlight: 'ow' },
      { word: 'now', phonetic: '/naʊ/', meaning: '现在；此刻', highlight: 'ow' },
      { word: 'flower', phonetic: '/ˈflaʊə(r)/', meaning: '花朵', highlight: 'ow' },
      { word: 'snow', phonetic: '/snəʊ/', meaning: '雪；下雪(发/əʊ/)', highlight: 'ow' },
      { word: 'bowl', phonetic: '/bəʊl/', meaning: '碗；深盘(发/əʊ/)', highlight: 'ow' },
      { word: 'slow', phonetic: '/sləʊ/', meaning: '缓慢的(发/əʊ/)', highlight: 'ow' },
    ],
  },
  {
    id: 'oi_oy',
    pattern: 'oi / oy',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/ɔɪ/'],
    ruleDescription: 'oi 和 oy 均发合口双元音 /ɔɪ/。口诀：oi 在中间（coin, oil），oy 在词尾（boy, toy）。',
    positionTip: 'oi 居词中，oy 居词尾。',
    examples: [
      { word: 'coin', phonetic: '/kɔɪn/', meaning: '硬币', highlight: 'oi' },
      { word: 'oil', phonetic: '/ɔɪl/', meaning: '石油；润滑油', highlight: 'oi' },
      { word: 'point', phonetic: '/pɔɪnt/', meaning: '要点；指点', highlight: 'oi' },
      { word: 'boy', phonetic: '/bɔɪ/', meaning: '男孩', highlight: 'oy' },
      { word: 'toy', phonetic: '/tɔɪ/', meaning: '玩具', highlight: 'oy' },
      { word: 'enjoy', phonetic: '/ɪnˈdʒɔɪ/', meaning: '享受；欣赏', highlight: 'oy' },
    ],
  },
  {
    id: 'au_aw',
    pattern: 'au / aw',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/ɔː/'],
    ruleDescription: 'au 和 aw 均发长后元音 /ɔː/。双唇收圆突出，发音深长饱满。',
    positionTip: 'au 多位于词首或词中；aw 多位于词尾或紧随字母 n, k, l。',
    examples: [
      { word: 'autumn', phonetic: '/ˈɔːtəm/', meaning: '秋天；秋季', highlight: 'au' },
      { word: 'pause', phonetic: '/pɔːz/', meaning: '暂停；停顿', highlight: 'au' },
      { word: 'August', phonetic: '/ɔːˈɡʌst/', meaning: '八月', highlight: 'Au' },
      { word: 'saw', phonetic: '/sɔː/', meaning: '锯子；看见', highlight: 'aw' },
      { word: 'draw', phonetic: '/drɔː/', meaning: '画画；拖拽', highlight: 'aw' },
      { word: 'law', phonetic: '/lɔː/', meaning: '法律；法规', highlight: 'aw' },
    ],
  },
  {
    id: 'ue_ui',
    pattern: 'ue / ui',
    category: 'vowel-vowel',
    categoryLabel: '元元组合',
    phonetics: ['/uː/'],
    ruleDescription: '字母组合 ue 与 ui 常发长后元音 /uː/（在某些辅音后带 /juː/）。',
    positionTip: 'ue 多在词尾，ui 多在词中。',
    examples: [
      { word: 'blue', phonetic: '/bluː/', meaning: '蓝色的', highlight: 'ue' },
      { word: 'glue', phonetic: '/ɡluː/', meaning: '胶水；粘贴', highlight: 'ue' },
      { word: 'clue', phonetic: '/kluː/', meaning: '线索；提示', highlight: 'ue' },
      { word: 'fruit', phonetic: '/fruːt/', meaning: '水果', highlight: 'ui' },
      { word: 'juice', phonetic: '/dʒuːs/', meaning: '果汁；果浆', highlight: 'ui' },
      { word: 'suit', phonetic: '/suːt/', meaning: '套装；适合', highlight: 'ui' },
    ],
  },

  // ==========================================
  // 二、元辅组合 (Vowel + Consonant & R-Controlled & Endings)
  // ==========================================
  {
    id: 'ir',
    pattern: 'ir',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ɜː/'],
    ruleDescription: 'ir 是极其核心的 r 卷舌元音组合，在重读音节中一律发长中元音 /ɜː/。舌身放平，舌中部稍抬。',
    positionTip: '常位于重读音节辅音之间。',
    examples: [
      { word: 'bird', phonetic: '/bɜːd/', meaning: '鸟；飞禽', highlight: 'ir' },
      { word: 'girl', phonetic: '/ɡɜːl/', meaning: '女孩；姑娘', highlight: 'ir' },
      { word: 'shirt', phonetic: '/ʃɜːt/', meaning: '衬衫；汗衫', highlight: 'ir' },
      { word: 'third', phonetic: '/θɜːd/', meaning: '第三；三分之一', highlight: 'ir' },
      { word: 'skirt', phonetic: '/skɜːt/', meaning: '裙子；短裙', highlight: 'ir' },
      { word: 'circus', phonetic: '/ˈsɜːkəs/', meaning: '马戏团', highlight: 'ir' },
    ],
  },
  {
    id: 'er',
    pattern: 'er',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ɜː/', '/ə/'],
    ruleDescription: 'er 在重读音节中发长音 /ɜː/（如 her, term）；在非重读音节中弱化为轻央元音 /ə/（如 teacher, water）。',
    positionTip: '重读音节在词中；非重读音节极常见于词尾名词后缀。',
    examples: [
      { word: 'her', phonetic: '/hɜː(r)/', meaning: '她的；她', highlight: 'er' },
      { word: 'term', phonetic: '/tɜːm/', meaning: '学期；术语', highlight: 'er' },
      { word: 'person', phonetic: '/ˈpɜːsn/', meaning: '人；个体', highlight: 'er' },
      { word: 'teacher', phonetic: '/ˈtiːtʃə(r)/', meaning: '教师(弱读/ə/)', highlight: 'er' },
      { word: 'water', phonetic: '/ˈwɔːtə(r)/', meaning: '水(弱读/ə/)', highlight: 'er' },
      { word: 'sister', phonetic: '/ˈsɪstə(r)/', meaning: '姐妹(弱读/ə/)', highlight: 'er' },
    ],
  },
  {
    id: 'ur',
    pattern: 'ur',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ɜː/'],
    ruleDescription: '字母组合 ur 在重读音节中通常发长中元音 /ɜː/。',
    positionTip: '多见于单词中间位置。',
    examples: [
      { word: 'nurse', phonetic: '/nɜːs/', meaning: '护士；照料', highlight: 'ur' },
      { word: 'turn', phonetic: '/tɜːn/', meaning: '转弯；轮流', highlight: 'ur' },
      { word: 'burn', phonetic: '/bɜːn/', meaning: '燃烧；烧伤', highlight: 'ur' },
      { word: 'hurt', phonetic: '/hɜːt/', meaning: '使受伤；疼痛', highlight: 'ur' },
      { word: 'purple', phonetic: '/ˈpɜːpl/', meaning: '紫色的', highlight: 'ur' },
      { word: 'curtain', phonetic: '/ˈkɜːtn/', meaning: '窗帘；门帘', highlight: 'ur' },
    ],
  },
  {
    id: 'ar',
    pattern: 'ar',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ɑː/'],
    ruleDescription: 'ar 字母组合在重读音节中通常发长后元音 /ɑː/（美音带卷舌 /ɑːr/）。而在 w 之后常变读为 /ɔː/（如 warm）。',
    positionTip: '多位于重读音节词中或词尾。',
    examples: [
      { word: 'car', phonetic: '/kɑː(r)/', meaning: '汽车', highlight: 'ar' },
      { word: 'park', phonetic: '/pɑːk/', meaning: '公园；停放', highlight: 'ar' },
      { word: 'star', phonetic: '/stɑː(r)/', meaning: '星星；明星', highlight: 'ar' },
      { word: 'dark', phonetic: '/dɑːk/', meaning: '黑暗的；暗处', highlight: 'ar' },
      { word: 'farm', phonetic: '/fɑːm/', meaning: '农场；耕作', highlight: 'ar' },
      { word: 'garden', phonetic: '/ˈɡɑːdn/', meaning: '花园；菜园', highlight: 'ar' },
    ],
  },
  {
    id: 'or',
    pattern: 'or',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ɔː/', '/ɜː/'],
    ruleDescription: 'or 组合在重读音节中一般发长后元音 /ɔː/；但在字母 w 之后经常变读为 /ɜː/（如 work, word）。',
    positionTip: '常位于词中或词尾。',
    examples: [
      { word: 'horse', phonetic: '/hɔːs/', meaning: '马', highlight: 'or' },
      { word: 'fork', phonetic: '/fɔːk/', meaning: '餐叉', highlight: 'or' },
      { word: 'sport', phonetic: '/spɔːt/', meaning: '体育运动', highlight: 'or' },
      { word: 'corn', phonetic: '/kɔːn/', meaning: '玉米；谷物', highlight: 'or' },
      { word: 'work', phonetic: '/wɜːk/', meaning: '工作(在w后读/ɜː/)', highlight: 'or' },
      { word: 'word', phonetic: '/wɜːd/', meaning: '单词；字词', highlight: 'or' },
    ],
  },
  {
    id: 'igh',
    pattern: 'igh',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/aɪ/'],
    ruleDescription: '极高频元辅组合！gh 完全不发音，字母 i 发字母本身音双元音 /aɪ/。口诀：igh 一起发 /aɪ/。',
    positionTip: '常位于词中，后常紧跟辅音字母 t。',
    examples: [
      { word: 'high', phonetic: '/haɪ/', meaning: '高的；高尚的', highlight: 'igh' },
      { word: 'night', phonetic: '/naɪt/', meaning: '夜晚；夜间', highlight: 'igh' },
      { word: 'light', phonetic: '/laɪt/', meaning: '光线；轻的', highlight: 'igh' },
      { word: 'fight', phonetic: '/faɪt/', meaning: '搏斗；战斗', highlight: 'igh' },
      { word: 'bright', phonetic: '/braɪt/', meaning: '明亮的；聪明的', highlight: 'igh' },
      { word: 'flight', phonetic: '/flaɪt/', meaning: '航班；飞行', highlight: 'igh' },
    ],
  },
  {
    id: 'eigh',
    pattern: 'eigh',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/eɪ/'],
    ruleDescription: '经典元辅组合！gh 不发音，组合整体发双元音 /eɪ/（与字母 A 读音一致）。',
    positionTip: '常见于基础数词及派生词汇。',
    examples: [
      { word: 'eight', phonetic: '/eɪt/', meaning: '八；八个', highlight: 'eigh' },
      { word: 'eighty', phonetic: '/ˈeɪti/', meaning: '八十', highlight: 'eigh' },
      { word: 'weigh', phonetic: '/weɪ/', meaning: '称重；重达', highlight: 'eigh' },
      { word: 'weight', phonetic: '/weɪt/', meaning: '重量；重力', highlight: 'eigh' },
      { word: 'neighbor', phonetic: '/ˈneɪbə(r)/', meaning: '邻居；相邻者', highlight: 'eigh' },
      { word: 'sleigh', phonetic: '/sleɪ/', meaning: '雪橇', highlight: 'eigh' },
    ],
  },
  {
    id: 'air_are',
    pattern: 'air / are',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/eə/'],
    ruleDescription: '字母组合 air 和 are 均发集中双元音 /eə/，从半开元音滑向放松的轻央元音。',
    positionTip: 'air 多居词中，are 多作为开音节词尾。',
    examples: [
      { word: 'hair', phonetic: '/heə(r)/', meaning: '头发；毛发', highlight: 'air' },
      { word: 'chair', phonetic: '/tʃeə(r)/', meaning: '椅子', highlight: 'air' },
      { word: 'air', phonetic: '/eə(r)/', meaning: '空气；大气', highlight: 'air' },
      { word: 'care', phonetic: '/keə(r)/', meaning: '照顾；在乎', highlight: 'are' },
      { word: 'share', phonetic: '/ʃeə(r)/', meaning: '分享；分担', highlight: 'are' },
      { word: 'dare', phonetic: '/deə(r)/', meaning: '敢于；胆敢', highlight: 'are' },
    ],
  },
  {
    id: 'ear_eer',
    pattern: 'ear / eer',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ɪə/'],
    ruleDescription: '字母组合 ear 和 eer 常见发集中双元音 /ɪə/。注意个别词 ear 发 /eə/（如 bear, pear）。',
    positionTip: '常见于独立单音节词或词尾。',
    examples: [
      { word: 'ear', phonetic: '/ɪə(r)/', meaning: '耳朵；听力', highlight: 'ear' },
      { word: 'hear', phonetic: '/hɪə(r)/', meaning: '听见；倾听', highlight: 'ear' },
      { word: 'near', phonetic: '/nɪə(r)/', meaning: '附近的；邻近', highlight: 'ear' },
      { word: 'deer', phonetic: '/dɪə(r)/', meaning: '鹿', highlight: 'eer' },
      { word: 'cheer', phonetic: '/tʃɪə(r)/', meaning: '欢呼；加油', highlight: 'eer' },
      { word: 'clear', phonetic: '/klɪə(r)/', meaning: '清晰的；放晴', highlight: 'ear' },
    ],
  },
  {
    id: 'tion',
    pattern: 'tion',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ʃn/'],
    ruleDescription: '英语最常见名词后缀组合！ti 发摩擦音 /ʃ/，元音 o 弱化甚至吞音，组合紧凑读作 /ʃn/。',
    positionTip: '位于多音节词的词尾，重音往往落在 tion 紧邻的前一个音节上。',
    examples: [
      { word: 'action', phonetic: '/ˈækʃn/', meaning: '行动；动作', highlight: 'tion' },
      { word: 'station', phonetic: '/ˈsteɪʃn/', meaning: '车站；所台', highlight: 'tion' },
      { word: 'nation', phonetic: '/ˈneɪʃn/', meaning: '国家；民族', highlight: 'tion' },
      { word: 'education', phonetic: '/ˌedʒuˈkeɪʃn/', meaning: '教育；培养', highlight: 'tion' },
      { word: 'question', phonetic: '/ˈkwestʃən/', meaning: '问题(s后读/tʃən/)', highlight: 'tion' },
      { word: 'attention', phonetic: '/əˈtenʃn/', meaning: '注意力；关照', highlight: 'tion' },
    ],
  },
  {
    id: 'sion',
    pattern: 'sion',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ʃn/', '/ʒn/'],
    ruleDescription: '若在辅音字母后发清辅音 /ʃn/（如 mission）；若在元音字母后浊化发 /ʒn/（如 decision, vision）。',
    positionTip: '常见于多音节名词词尾。',
    examples: [
      { word: 'decision', phonetic: '/dɪˈsɪʒn/', meaning: '决定；决断(发/ʒn/)', highlight: 'sion' },
      { word: 'television', phonetic: '/ˈtelɪvɪʒn/', meaning: '电视(发/ʒn/)', highlight: 'sion' },
      { word: 'vision', phonetic: '/ˈvɪʒn/', meaning: '视力；远见(发/ʒn/)', highlight: 'sion' },
      { word: 'conclusion', phonetic: '/kənˈkluːʒn/', meaning: '结论；推论', highlight: 'sion' },
      { word: 'mission', phonetic: '/ˈmɪʃn/', meaning: '任务；使命(发/ʃn/)', highlight: 'sion' },
      { word: 'discussion', phonetic: '/dɪˈskʌʃn/', meaning: '讨论(发/ʃn/)', highlight: 'sion' },
    ],
  },
  {
    id: 'ture',
    pattern: 'ture',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/tʃə/'],
    ruleDescription: '常见名词后缀，在非重读音节中统一读作 /tʃə(r)/。',
    positionTip: '固定位于词尾。',
    examples: [
      { word: 'picture', phonetic: '/ˈpɪktʃə(r)/', meaning: '图画；照片', highlight: 'ture' },
      { word: 'nature', phonetic: '/ˈneɪtʃə(r)/', meaning: '自然；天性', highlight: 'ture' },
      { word: 'future', phonetic: '/ˈfjuːtʃə(r)/', meaning: '未来；前途', highlight: 'ture' },
      { word: 'culture', phonetic: '/ˈkʌltʃə(r)/', meaning: '文化；文明', highlight: 'ture' },
      { word: 'capture', phonetic: '/ˈkæptʃə(r)/', meaning: '捕获；拍摄', highlight: 'ture' },
      { word: 'feature', phonetic: '/ˈfiːtʃə(r)/', meaning: '特征；特色', highlight: 'ture' },
    ],
  },
  {
    id: 'sure',
    pattern: 'sure',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ʒə/'],
    ruleDescription: '名词词尾组合，在元音后常读作浊辅音 /ʒə(r)/；少部分词读清音 /ʃə(r)/（如 pressure）。',
    positionTip: '多见于多音节抽象名词词尾。',
    examples: [
      { word: 'measure', phonetic: '/ˈmeʒə(r)/', meaning: '测量；措施', highlight: 'sure' },
      { word: 'pleasure', phonetic: '/ˈpleʒə(r)/', meaning: '愉快；荣幸', highlight: 'sure' },
      { word: 'leisure', phonetic: '/ˈleʒə(r)/', meaning: '闲暇；休闲', highlight: 'sure' },
      { word: 'treasure', phonetic: '/ˈtreʒə(r)/', meaning: '宝藏；珍视', highlight: 'sure' },
      { word: 'exposure', phonetic: '/ɪkˈspəʊʒə(r)/', meaning: '暴露；曝光', highlight: 'sure' },
      { word: 'pressure', phonetic: '/ˈpreʃə(r)/', meaning: '压力(读/ʃə/)', highlight: 'sure' },
    ],
  },
  {
    id: 'al_all',
    pattern: 'al / all',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/ɔːl/'],
    ruleDescription: '字母 a 在 ll 前或 l+辅音前常被同化发深长圆唇元音 /ɔː/，组合发 /ɔːl/。在 walk, talk 中 l 不发音。',
    positionTip: '常见于单音节或重读音节中。',
    examples: [
      { word: 'ball', phonetic: '/bɔːl/', meaning: '球；舞会', highlight: 'all' },
      { word: 'tall', phonetic: '/tɔːl/', meaning: '高的', highlight: 'all' },
      { word: 'call', phonetic: '/kɔːl/', meaning: '打电话；呼喊', highlight: 'all' },
      { word: 'fall', phonetic: '/fɔːl/', meaning: '落下；跌倒', highlight: 'all' },
      { word: 'walk', phonetic: '/wɔːk/', meaning: '行走(l不发音)', highlight: 'al' },
      { word: 'chalk', phonetic: '/tʃɔːk/', meaning: '粉笔(l不发音)', highlight: 'al' },
    ],
  },
  {
    id: 'ous',
    pattern: 'ous',
    category: 'vowel-consonant',
    categoryLabel: '元辅组合',
    phonetics: ['/əs/'],
    ruleDescription: '极常见形容词后缀组合，位于非重读音节，元音弱化为短央音 /ə/，组合读作 /əs/。',
    positionTip: '固定出现在形容词词尾。',
    examples: [
      { word: 'famous', phonetic: '/ˈfeɪməs/', meaning: '著名的', highlight: 'ous' },
      { word: 'dangerous', phonetic: '/ˈdeɪndʒərəs/', meaning: '危险的', highlight: 'ous' },
      { word: 'nervous', phonetic: '/ˈnɜːvəs/', meaning: '紧张的', highlight: 'ous' },
      { word: 'delicious', phonetic: '/dɪˈlɪʃəs/', meaning: '美味的', highlight: 'ous' },
      { word: 'continuous', phonetic: '/kənˈtɪnjuəs/', meaning: '持续的', highlight: 'ous' },
      { word: 'serious', phonetic: '/ˈsɪəriəs/', meaning: '严肃的；严重的', highlight: 'ous' },
    ],
  },

  // ==========================================
  // 三、辅辅组合 (Consonant Digraphs & Blends)
  // ==========================================
  {
    id: 'sh',
    pattern: 'sh',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/ʃ/'],
    ruleDescription: '经典的辅音字母组合，舌端靠近硬腭前部，双唇略突微圆，气流摩擦而出发出“嘘”声。',
    positionTip: '可位于词首、词中或词尾。',
    examples: [
      { word: 'ship', phonetic: '/ʃɪp/', meaning: '轮船；舰艇', highlight: 'sh' },
      { word: 'fish', phonetic: '/fɪʃ/', meaning: '鱼；钓鱼', highlight: 'sh' },
      { word: 'shop', phonetic: '/ʃɒp/', meaning: '商店；购物', highlight: 'sh' },
      { word: 'brush', phonetic: '/brʌʃ/', meaning: '刷子；刷洗', highlight: 'sh' },
      { word: 'shine', phonetic: '/ʃaɪn/', meaning: '照耀；发光', highlight: 'sh' },
      { word: 'wish', phonetic: '/wɪʃ/', meaning: '希望；祝愿', highlight: 'sh' },
    ],
  },
  {
    id: 'ch_tch',
    pattern: 'ch / tch',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/tʃ/', '/k/'],
    ruleDescription: 'ch 和 tch 绝大多数发破擦清辅音 /tʃ/（如 chair, watch）。在希腊语源词中发 /k/（如 school, chemistry）。',
    positionTip: 'ch 可在词首、词尾；tch 习惯紧跟短元音后位于词尾。',
    examples: [
      { word: 'chair', phonetic: '/tʃeə(r)/', meaning: '椅子', highlight: 'ch' },
      { word: 'chat', phonetic: '/tʃæt/', meaning: '聊天；闲谈', highlight: 'ch' },
      { word: 'catch', phonetic: '/kætʃ/', meaning: '抓住；赶上', highlight: 'tch' },
      { word: 'watch', phonetic: '/wɒtʃ/', meaning: '手表；观看', highlight: 'tch' },
      { word: 'school', phonetic: '/skuːl/', meaning: '学校(读/k/)', highlight: 'ch' },
      { word: 'chemistry', phonetic: '/ˈkemɪstri/', meaning: '化学(读/k/)', highlight: 'ch' },
    ],
  },
  {
    id: 'th_voiceless',
    pattern: 'th (清音)',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/θ/'],
    ruleDescription: '咬舌清辅音！舌尖轻探于上下门齿之间，气流轻吹而出，声带不振动。多见于实词。',
    positionTip: '常见于数词、名词、形容词中。',
    examples: [
      { word: 'thank', phonetic: '/θæŋk/', meaning: '感谢；感激', highlight: 'th' },
      { word: 'think', phonetic: '/θɪŋk/', meaning: '思考；认为', highlight: 'th' },
      { word: 'three', phonetic: '/θriː/', meaning: '三；三个', highlight: 'th' },
      { word: 'thin', phonetic: '/θɪn/', meaning: '瘦的；细薄的', highlight: 'th' },
      { word: 'tooth', phonetic: '/tuːθ/', meaning: '牙齿', highlight: 'th' },
      { word: 'math', phonetic: '/mæθ/', meaning: '数学', highlight: 'th' },
    ],
  },
  {
    id: 'th_voiced',
    pattern: 'th (浊音)',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/ð/'],
    ruleDescription: '咬舌浊辅音！舌尖放上下齿间，气流挤出的同时声带强烈振动。多见于虚词及词尾带 e 动词。',
    positionTip: '常见于代词、冠词、介词等语法词及词中。',
    examples: [
      { word: 'this', phonetic: '/ðɪs/', meaning: '这个', highlight: 'th' },
      { word: 'that', phonetic: '/ðæt/', meaning: '那个', highlight: 'th' },
      { word: 'they', phonetic: '/ðeɪ/', meaning: '他们；它们', highlight: 'th' },
      { word: 'father', phonetic: '/ˈfɑːðə(r)/', meaning: '父亲；爸爸', highlight: 'th' },
      { word: 'mother', phonetic: '/ˈmʌðə(r)/', meaning: '母亲；妈妈', highlight: 'th' },
      { word: 'with', phonetic: '/wɪð/', meaning: '和…一起；用', highlight: 'th' },
    ],
  },
  {
    id: 'ph',
    pattern: 'ph',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/f/'],
    ruleDescription: '希腊语词源组合，字母组合 ph 一律发摩擦清辅音 /f/，上齿轻抵下唇吹气。',
    positionTip: '可位于词首、词中或词尾。',
    examples: [
      { word: 'phone', phonetic: '/fəʊn/', meaning: '电话；手机', highlight: 'ph' },
      { word: 'photo', phonetic: '/ˈfəʊtəʊ/', meaning: '照片；相片', highlight: 'ph' },
      { word: 'elephant', phonetic: '/ˈelɪfənt/', meaning: '大象', highlight: 'ph' },
      { word: 'dolphin', phonetic: '/ˈdɒlfɪn/', meaning: '海豚', highlight: 'ph' },
      { word: 'graph', phonetic: '/ɡrɑːf/', meaning: '图表；曲线图', highlight: 'ph' },
      { word: 'alphabet', phonetic: '/ˈælfəbet/', meaning: '字母表', highlight: 'ph' },
    ],
  },
  {
    id: 'ck',
    pattern: 'ck',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/k/'],
    ruleDescription: 'ck 是典型的短元音守门员！紧跟在单短元音之后，发清脆的爆破清辅音 /k/。',
    positionTip: '固定出现在短元音之后的单音节词尾或词中。',
    examples: [
      { word: 'black', phonetic: '/blæk/', meaning: '黑色的', highlight: 'ck' },
      { word: 'duck', phonetic: '/dʌk/', meaning: '鸭子', highlight: 'ck' },
      { word: 'rock', phonetic: '/rɒk/', meaning: '岩石；摇滚', highlight: 'ck' },
      { word: 'clock', phonetic: '/klɒk/', meaning: '时钟；座钟', highlight: 'ck' },
      { word: 'lock', phonetic: '/lɒk/', meaning: '锁上；水闸', highlight: 'ck' },
      { word: 'neck', phonetic: '/nek/', meaning: '脖子；颈部', highlight: 'ck' },
    ],
  },
  {
    id: 'dge',
    pattern: 'dge',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/dʒ/'],
    ruleDescription: '字母组合 dge 紧跟在短元音之后，发破擦浊辅音 /dʒ/。d 保持前面的元音为短元音。',
    positionTip: '固定位于单词词尾。',
    examples: [
      { word: 'bridge', phonetic: '/brɪdʒ/', meaning: '桥梁', highlight: 'dge' },
      { word: 'judge', phonetic: '/dʒʌdʒ/', meaning: '法官；裁判', highlight: 'dge' },
      { word: 'edge', phonetic: '/edʒ/', meaning: '边缘；刃', highlight: 'dge' },
      { word: 'badge', phonetic: '/bædʒ/', meaning: '徽章；证章', highlight: 'dge' },
      { word: 'fridge', phonetic: '/frɪdʒ/', meaning: '冰箱', highlight: 'dge' },
      { word: 'knowledge', phonetic: '/ˈnɒlɪdʒ/', meaning: '知识；学问', highlight: 'dge' },
    ],
  },
  {
    id: 'ge',
    pattern: 'ge',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/dʒ/'],
    ruleDescription: '软音 g 规则：字母 g 在 e 之前常软化发破擦浊辅音 /dʒ/。',
    positionTip: '常见于单词词尾。',
    examples: [
      { word: 'page', phonetic: '/peɪdʒ/', meaning: '页面；页码', highlight: 'ge' },
      { word: 'age', phonetic: '/eɪdʒ/', meaning: '年龄；时代', highlight: 'ge' },
      { word: 'orange', phonetic: '/ˈɒrɪndʒ/', meaning: '橙子；橙色的', highlight: 'ge' },
      { word: 'large', phonetic: '/lɑːdʒ/', meaning: '巨大的；广泛的', highlight: 'ge' },
      { word: 'huge', phonetic: '/hjuːdʒ/', meaning: '庞大的；巨大的', highlight: 'ge' },
      { word: 'village', phonetic: '/ˈvɪlɪdʒ/', meaning: '乡村；村庄', highlight: 'ge' },
    ],
  },
  {
    id: 'wh',
    pattern: 'wh',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/w/', '/h/'],
    ruleDescription: 'wh 在大多情况下发双唇半元音 /w/（h不发音）；但在元音字母 o 前通常发 /h/（w不发音，如 who, whose）。',
    positionTip: '固定位于疑问词及词首。',
    examples: [
      { word: 'what', phonetic: '/wɒt/', meaning: '什么', highlight: 'wh' },
      { word: 'white', phonetic: '/waɪt/', meaning: '白色的', highlight: 'wh' },
      { word: 'wheel', phonetic: '/wiːl/', meaning: '轮子；方向盘', highlight: 'wh' },
      { word: 'who', phonetic: '/huː/', meaning: '谁(在o前读/h/)', highlight: 'wh' },
      { word: 'whose', phonetic: '/huːz/', meaning: '谁的', highlight: 'wh' },
      { word: 'whole', phonetic: '/həʊl/', meaning: '整个的；完整的', highlight: 'wh' },
    ],
  },
  {
    id: 'kn',
    pattern: 'kn',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/n/'],
    ruleDescription: '经典静音组合！位于词首时 k 完全不发音，只发齿龈鼻音 /n/。',
    positionTip: '固定出现在单词开头。',
    examples: [
      { word: 'know', phonetic: '/nəʊ/', meaning: '知道；了解', highlight: 'kn' },
      { word: 'knife', phonetic: '/naɪf/', meaning: '小刀；餐刀', highlight: 'kn' },
      { word: 'knee', phonetic: '/niː/', meaning: '膝盖', highlight: 'kn' },
      { word: 'knock', phonetic: '/nɒk/', meaning: '敲门；撞击', highlight: 'kn' },
      { word: 'knot', phonetic: '/nɒt/', meaning: '绳结；打结', highlight: 'kn' },
      { word: 'knight', phonetic: '/naɪt/', meaning: '骑士；爵士', highlight: 'kn' },
    ],
  },
  {
    id: 'wr',
    pattern: 'wr',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/r/'],
    ruleDescription: '经典静音组合！位于词首时 w 完全不发音，只发齿龈后部通音 /r/。',
    positionTip: '固定出现在单词开头。',
    examples: [
      { word: 'write', phonetic: '/raɪt/', meaning: '书写；创作', highlight: 'wr' },
      { word: 'wrong', phonetic: '/rɒŋ/', meaning: '错误的；不当的', highlight: 'wr' },
      { word: 'wrist', phonetic: '/rɪst/', meaning: '手腕；腕关节', highlight: 'wr' },
      { word: 'wrap', phonetic: '/ræp/', meaning: '包裹；缠绕', highlight: 'wr' },
      { word: 'wreck', phonetic: '/rek/', meaning: '残骸；失事', highlight: 'wr' },
      { word: 'wrap', phonetic: '/ræp/', meaning: '包，包裹', highlight: 'wr' },
    ],
  },
  {
    id: 'mb',
    pattern: 'mb',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/m/'],
    ruleDescription: '经典静音组合！在词尾时字母 b 完全不发音，只发双唇鼻音 /m/。',
    positionTip: '固定出现在单音节词词尾。',
    examples: [
      { word: 'climb', phonetic: '/klaɪm/', meaning: '攀登；爬', highlight: 'mb' },
      { word: 'bomb', phonetic: '/bɒm/', meaning: '炸弹', highlight: 'mb' },
      { word: 'thumb', phonetic: '/θʌm/', meaning: '大拇指', highlight: 'mb' },
      { word: 'lamb', phonetic: '/læm/', meaning: '羔羊；小羊', highlight: 'mb' },
      { word: 'comb', phonetic: '/kəʊm/', meaning: '梳子；梳头', highlight: 'mb' },
      { word: 'tomb', phonetic: '/tuːm/', meaning: '坟墓；墓穴', highlight: 'mb' },
    ],
  },
  {
    id: 'ng',
    pattern: 'ng',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/ŋ/'],
    ruleDescription: '字母组合 ng 发软腭鼻音 /ŋ/，舌后部抵软腭，气流由鼻腔透出，声带振动。',
    positionTip: '常见于词尾及动词 -ing 形式。',
    examples: [
      { word: 'sing', phonetic: '/sɪŋ/', meaning: '唱歌', highlight: 'ng' },
      { word: 'king', phonetic: '/kɪŋ/', meaning: '国王', highlight: 'ng' },
      { word: 'ring', phonetic: '/rɪŋ/', meaning: '戒指；铃声', highlight: 'ng' },
      { word: 'long', phonetic: '/lɒŋ/', meaning: '长的；长久的', highlight: 'ng' },
      { word: 'song', phonetic: '/sɒŋ/', meaning: '歌曲', highlight: 'ng' },
      { word: 'spring', phonetic: '/sprɪŋ/', meaning: '春天；泉水', highlight: 'ng' },
    ],
  },
  {
    id: 'nk',
    pattern: 'nk',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/ŋk/'],
    ruleDescription: '字母组合 nk 发 /ŋk/，n 被后面的 k 同化发鼻音 /ŋ/，紧跟爆发音 /k/。',
    positionTip: '固定位于词中或词尾。',
    examples: [
      { word: 'bank', phonetic: '/bæŋk/', meaning: '银行；河岸', highlight: 'nk' },
      { word: 'think', phonetic: '/θɪŋk/', meaning: '思考；认为', highlight: 'nk' },
      { word: 'pink', phonetic: '/pɪŋk/', meaning: '粉色的', highlight: 'nk' },
      { word: 'thank', phonetic: '/θæŋk/', meaning: '感谢', highlight: 'nk' },
      { word: 'drink', phonetic: '/drɪŋk/', meaning: '喝水；饮料', highlight: 'nk' },
      { word: 'sink', phonetic: '/sɪŋk/', meaning: '下沉；水槽', highlight: 'nk' },
    ],
  },
  {
    id: 'qu',
    pattern: 'qu',
    category: 'consonant-consonant',
    categoryLabel: '辅辅组合',
    phonetics: ['/kw/'],
    ruleDescription: '字母 q 几乎永远与 u 结伴出现，发合音 /kw/。类似于 /k/ 与 /w/ 的快速连读。',
    positionTip: '绝大多数位于词首。',
    examples: [
      { word: 'queen', phonetic: '/kwiːn/', meaning: '女王；王后', highlight: 'qu' },
      { word: 'quick', phonetic: '/kwɪk/', meaning: '快速的；敏捷的', highlight: 'qu' },
      { word: 'quiet', phonetic: '/ˈkwaɪət/', meaning: '安静的；宁静的', highlight: 'qu' },
      { word: 'quiz', phonetic: '/kwɪz/', meaning: '测验；小型考试', highlight: 'qu' },
      { word: 'quite', phonetic: '/kwaɪt/', meaning: '相当；十分', highlight: 'qu' },
      { word: 'quarter', phonetic: '/ˈkwɔːtə(r)/', meaning: '四分之一；一刻钟', highlight: 'qu' },
    ],
  },
]
