import type { RootItem } from '@/types'

export const BUILTIN_ROOTS: RootItem[] = [
  {
    id: 'root_spect',
    form: 'spect / spic',
    phonetic: '/spekt/',
    meaning: '看 / 观察 / 视角',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 specere / spectare，原意为“仔细凝视、观察”。由“眼之所见”自然引申出外观、审视、观点与前景等多维认知概念。',
    derivationNote: '搭配不同方向前缀（in- 向内、re- 向后、pro- 向前、per- 穿透）可精准构建庞大的视觉与认知词族。',
    words: [
      {
        name: 'inspect',
        phonetic: '/ɪnˈspekt/',
        breakdown: 'in- (向内) + spect (看)',
        meaning: 'v. 检查；视察；检阅',
        example: {
          en: 'Customs officials inspect all luggage carefully.',
          cn: '海关人员仔细检查所有行李。',
        },
      },
      {
        name: 'respect',
        phonetic: '/rɪˈspekt/',
        breakdown: 're- (再/回) + spect (看)',
        meaning: 'v./n. 尊重；敬重；方面',
        example: {
          en: 'We should always respect different cultures and opinions.',
          cn: '我们应当始终尊重不同的文化与观点。',
        },
      },
      {
        name: 'perspective',
        phonetic: '/pərˈspektɪv/',
        breakdown: 'per- (透过) + spect (看) + -ive',
        meaning: 'n. 视角；洞察力；透视画法',
        example: {
          en: 'Traveling abroad gives you a fresh perspective on life.',
          cn: '出国旅行会赋予你对生活全新的视角。',
        },
      },
      {
        name: 'prospect',
        phonetic: '/ˈprɑːspekt/',
        breakdown: 'pro- (向前) + spect (看)',
        meaning: 'n. 前景；前途；期望',
        example: {
          en: 'The economic prospects for next year look bright.',
          cn: '明年的经济前景看起来十分光明。',
        },
      },
      {
        name: 'spectacle',
        phonetic: '/ˈspektəkl/',
        breakdown: 'spect (看) + -acle (物/器具)',
        meaning: 'n. 精彩场面；奇观；眼镜(pl.)',
        example: {
          en: 'The solar eclipse was a truly breathtaking spectacle.',
          cn: '日食是一场令人叹为观止的壮丽奇观。',
        },
      },
      {
        name: 'spectator',
        phonetic: '/ˈspekteɪtər/',
        breakdown: 'spect (看) + -ator (人)',
        meaning: 'n. 现场观众；旁观者',
        example: {
          en: 'Thousands of spectators cheered for the winning team.',
          cn: '数万名现场观众为获胜的队伍欢呼。',
        },
      },
    ],
  },
  {
    id: 'root_struct',
    form: 'struct',
    phonetic: '/strʌkt/',
    meaning: '建造 / 构成 / 组织',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 struere（堆叠、建造、组织）。不仅用于物理建筑搭建，更广泛引申至思维、制度与知识体系的结构化塑造。',
    derivationNote: '加上 con-（共同建造）、de-（拆解破坏）、in-（在内部注入知识）即可构造成形形色色的体系词。',
    words: [
      {
        name: 'construct',
        phonetic: '/kənˈstrʌkt/',
        breakdown: 'con- (共同) + struct (建造)',
        meaning: 'v. 建设；构建；创立',
        example: {
          en: 'The engineers began to construct a modern railway bridge.',
          cn: '工程师们开始建造一座现代化的铁路桥梁。',
        },
      },
      {
        name: 'instruct',
        phonetic: '/ɪnˈstrʌkt/',
        breakdown: 'in- (向内) + struct (建造)',
        meaning: 'v. 指导；指示；教授',
        example: {
          en: 'The coach instructed the team on new defensive tactics.',
          cn: '教练向队员们传授了全新的防守战术。',
        },
      },
      {
        name: 'structure',
        phonetic: '/ˈstrʌktʃər/',
        breakdown: 'struct (建造) + -ure (名词后缀)',
        meaning: 'n. 结构；体系；建筑物',
        example: {
          en: 'Understanding data structures is essential for developers.',
          cn: '理解数据结构是开发者必不可少的核心能力。',
        },
      },
      {
        name: 'destruct',
        phonetic: '/dɪˈstrʌkt/',
        breakdown: 'de- (破坏/向下) + struct (建造)',
        meaning: 'v. 破坏；自毁；消灭',
        example: {
          en: 'The spacecraft was programmed to self-destruct if off course.',
          cn: '飞船被设定为偏离航线时自动启动自毁程序。',
        },
      },
      {
        name: 'obstruct',
        phonetic: '/əbˈstrʌkt/',
        breakdown: 'ob- (反向/阻碍) + struct (建造)',
        meaning: 'v. 阻碍；妨碍；阻塞',
        example: {
          en: 'Fallen trees obstructed traffic on the highway.',
          cn: '倒下的树木阻断了高速公路上的交通。',
        },
      },
    ],
  },
  {
    id: 'root_port',
    form: 'port',
    phonetic: '/pɔːrt/',
    meaning: '携带 / 搬运 / 港口',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 portare（搬运、运送）和 portus（港口、大门）。是商业贸易、交通运输与信息传递的核心基石。',
    derivationNote: '配合 ex-（向外运）、im-（向内运）、trans-（跨越运）构成了国际物流与商贸的核心骨架。',
    words: [
      {
        name: 'export',
        phonetic: '/ˈekspɔːrt/',
        breakdown: 'ex- (出/外) + port (运)',
        meaning: 'v./n. 出口；输出',
        example: {
          en: 'The country exports high-tech electronic equipment worldwide.',
          cn: '该国向全球出口高科技电子设备。',
        },
      },
      {
        name: 'import',
        phonetic: '/ˈɪmpɔːrt/',
        breakdown: 'im- (入/内) + port (运)',
        meaning: 'v./n. 进口；输入；重要性',
        example: {
          en: 'They import premium coffee beans from South America.',
          cn: '他们从南美洲进口高品质咖啡豆。',
        },
      },
      {
        name: 'transport',
        phonetic: '/ˈtrænspɔːrt/',
        breakdown: 'trans- (跨越) + port (运)',
        meaning: 'v./n. 运输；传送；交通工具',
        example: {
          en: 'Public transport helps reduce urban carbon emissions.',
          cn: '公共交通有助于减少城市碳排放。',
        },
      },
      {
        name: 'portable',
        phonetic: '/ˈpɔːrtəbl/',
        breakdown: 'port (搬运) + -able (可...的)',
        meaning: 'adj. 便携式的；轻便的',
        example: {
          en: 'Laptops and portable chargers make remote work seamless.',
          cn: '笔记本电脑与便携式充电宝让远程办公变得轻松无缝。',
        },
      },
      {
        name: 'support',
        phonetic: '/səˈpɔːrt/',
        breakdown: 'sub- (在下方) + port (托运/支撑)',
        meaning: 'v./n. 支持；支撑；养活',
        example: {
          en: 'Family members always support each other during hard times.',
          cn: '家人在艰难时刻总是相互支持与鼓励。',
        },
      },
    ],
  },
  {
    id: 'root_tract',
    form: 'tract',
    phonetic: '/trækt/',
    meaning: '拉 / 抽 / 吸引',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 trahere / tractus（拉引、拖曳、抽取）。由“外力拉动”引申为注意力的吸引、概念的抽象提炼与契约订立。',
    derivationNote: '从物理上的拖拉机（tractor）到思维上的抽象（abstract），词义跨度展现了拉引的丰富延伸。',
    words: [
      {
        name: 'attract',
        phonetic: '/əˈtrækt/',
        breakdown: 'ad- (向着) + tract (拉)',
        meaning: 'v. 吸引；引起注意',
        example: {
          en: 'The coastal festival attracts thousands of tourists every summer.',
          cn: '这个沿海节日每年夏天吸引成千上万的游客。',
        },
      },
      {
        name: 'abstract',
        phonetic: '/ˈæbstrækt/',
        breakdown: 'ab- (离开/抽离) + tract (拉)',
        meaning: 'adj. 抽象的 n. 摘要 v. 提取',
        example: {
          en: 'The research paper begins with a concise abstract of findings.',
          cn: '这篇研究论文以对研究发现的简明摘要开篇。',
        },
      },
      {
        name: 'contract',
        phonetic: '/ˈkɑːntrækt/',
        breakdown: 'con- (共同) + tract (拉到一起)',
        meaning: 'n. 合同；契约 v. 收缩；感染',
        example: {
          en: 'Both parties signed the employment contract yesterday.',
          cn: '双方昨天正式签署了雇佣合同。',
        },
      },
      {
        name: 'extract',
        phonetic: '/ɪkˈstrækt/',
        breakdown: 'ex- (出) + tract (拉/抽)',
        meaning: 'v. 提取；拔出；摘录 n. 提取物',
        example: {
          en: 'Scientists extract pure plant oils for medical purposes.',
          cn: '科学家们提取纯植物精油用于医疗用途。',
        },
      },
      {
        name: 'distract',
        phonetic: '/dɪˈstrækt/',
        breakdown: 'dis- (分散) + tract (拉)',
        meaning: 'v. 分散注意力；使分心',
        example: {
          en: 'Loud background noises can easily distract your focus.',
          cn: '嘈杂的背景噪音很容易分散你的注意力。',
        },
      },
    ],
  },
  {
    id: 'root_dict',
    form: 'dict / dic',
    phonetic: '/dɪkt/',
    meaning: '说 / 声明 / 宣称',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 dicere / dictus（说话、言明、宣告）。与人类法律条令、词典编纂与语言预言紧密关联。',
    derivationNote: 'pre-（预先说 → 预测）、contra-（反着说 → 反驳）、ad-（沉迷于某宣告 → 上瘾）。',
    words: [
      {
        name: 'predict',
        phonetic: '/prɪˈdɪkt/',
        breakdown: 'pre- (预先) + dict (说)',
        meaning: 'v. 预测；预言',
        example: {
          en: 'Meteorologists predict heavy rainfall over the weekend.',
          cn: '气象学家预测周末将有强降雨。',
        },
      },
      {
        name: 'contradict',
        phonetic: '/ˌkɑːntrəˈdɪkt/',
        breakdown: 'contra- (相反) + dict (说)',
        meaning: 'v. 反驳；与...相矛盾',
        example: {
          en: 'The experimental results contradict previous theories.',
          cn: '实验结果与先前的理论产生了矛盾。',
        },
      },
      {
        name: 'dictionary',
        phonetic: '/ˈdɪkʃəneri/',
        breakdown: 'dict (言语) + -ion + -ary (工具书)',
        meaning: 'n. 词典；字典',
        example: {
          en: 'Consult an authentic dictionary to verify word definitions.',
          cn: '查阅权威词典以核实单词的确切定义。',
        },
      },
      {
        name: 'dictate',
        phonetic: '/ˈdɪkteɪt/',
        breakdown: 'dict (说/命令) + -ate (动词后缀)',
        meaning: 'v. 口授；命令；决定',
        example: {
          en: 'The manager dictated a quick memo to his assistant.',
          cn: '经理向助理口授了一份简短备忘录。',
        },
      },
      {
        name: 'verdict',
        phonetic: '/ˈvɜːrdɪkt/',
        breakdown: 'ver- (真实) + dict (说/判决)',
        meaning: 'n. 裁决；判决；定论',
        example: {
          en: 'The jury reached a unanimous guilty verdict.',
          cn: '陪审团一致作出了有罪裁决。',
        },
      },
    ],
  },
  {
    id: 'root_vis',
    form: 'vis / vid',
    phonetic: '/vɪz/',
    meaning: '看 / 观察 / 查见',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 videre / visus（看见、观察）。与 spect（注视）相比，vis 侧重于直观的感知、影像与远见洞察。',
    derivationNote: '衍生出现代科技中极高频的 video（视频）、vision（视觉/远见）与 visible（可见的）。',
    words: [
      {
        name: 'visible',
        phonetic: '/ˈvɪzəbl/',
        breakdown: 'vis (看) + -ible (可...的)',
        meaning: 'adj. 可见的；明显的',
        example: {
          en: 'The bright stars were clearly visible in the night sky.',
          cn: '夜空中明亮的繁星清晰可见。',
        },
      },
      {
        name: 'vision',
        phonetic: '/ˈvɪʒn/',
        breakdown: 'vis (看) + -ion (名词后缀)',
        meaning: 'n. 视力；远见；眼光；幻象',
        example: {
          en: 'A great leader possesses a clear vision for the future.',
          cn: '优秀的领导者对未来拥有清晰长远的战略眼光。',
        },
      },
      {
        name: 'revise',
        phonetic: '/rɪˈvaɪz/',
        breakdown: 're- (再/重) + vis (看/审视)',
        meaning: 'v. 修订；复习；修改',
        example: {
          en: 'Students revise their notes thoroughly before final exams.',
          cn: '学生们在期末考试前认真复习笔记。',
        },
      },
      {
        name: 'supervise',
        phonetic: '/ˈsuːpərvaɪz/',
        breakdown: 'super- (在上面) + vis (看/监视)',
        meaning: 'v. 监督；管理；指导',
        example: {
          en: 'Senior managers supervise multiple team projects simultaneously.',
          cn: '高级经理同时监督指导多个团队项目的推进。',
        },
      },
      {
        name: 'evidence',
        phonetic: '/ˈevɪdəns/',
        breakdown: 'e- (出) + vid (看) + -ence (看出来的证据)',
        meaning: 'n. 证据；迹象；证明',
        example: {
          en: 'The detective discovered crucial evidence at the scene.',
          cn: '侦探在现场发现了至关重要的破案证据。',
        },
      },
    ],
  },
  {
    id: 'root_mit',
    form: 'mit / miss',
    phonetic: '/mɪt/',
    meaning: '送 / 发射 / 允许',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 mittere / missus（送出、释放、派遣）。是现代通信、任务执行与许可证制度的基础构词根。',
    derivationNote: 'ad-（允许进入 → 录取）、trans-（传送信号 → 传输）、sub-（送上去 → 提交）。',
    words: [
      {
        name: 'transmit',
        phonetic: '/trænzˈmɪt/',
        breakdown: 'trans- (穿过) + mit (送)',
        meaning: 'v. 传输；传送；传播',
        example: {
          en: 'Satellites transmit high-speed data across continents.',
          cn: '人造卫星在各大洲之间高速传输数据。',
        },
      },
      {
        name: 'admit',
        phonetic: '/ədˈmɪt/',
        breakdown: 'ad- (向着) + mit (送入/准入)',
        meaning: 'v. 承认；准许进入；录取',
        example: {
          en: 'She was proud to be admitted to top medical school.',
          cn: '她为被顶尖医学院正式录取而倍感自豪。',
        },
      },
      {
        name: 'submit',
        phonetic: '/səbˈmɪt/',
        breakdown: 'sub- (自下而上) + mit (送递)',
        meaning: 'v. 提交；呈递；屈服',
        example: {
          en: 'Please submit your quarterly report before Friday afternoon.',
          cn: '请在周五下午之前提交您的季度总结报告。',
        },
      },
      {
        name: 'mission',
        phonetic: '/ˈmɪʃn/',
        breakdown: 'miss (派遣/送出) + -ion',
        meaning: 'n. 任务；使命；代表团',
        example: {
          en: 'The astronaut crew completed their space station mission successfully.',
          cn: '宇航员乘组圆满完成了他们的空间站使命。',
        },
      },
      {
        name: 'permit',
        phonetic: '/pərˈmɪt/',
        breakdown: 'per- (完全) + mit (放行/送出)',
        meaning: 'v. 允许；准许 n. 许可证',
        example: {
          en: 'You need a valid parking permit to enter this area.',
          cn: '您需要持有有效的停车许可证方可进入该区域。',
        },
      },
    ],
  },
  {
    id: 'root_fac',
    form: 'fac / fact / fect',
    phonetic: '/fækt/',
    meaning: '做 / 制造 / 产生',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 facere / factus（做、制作、达成）。是表示“行动制造”与“事实发生”最丰富的经典大词根。',
    derivationNote: 'factory（工厂）、factor（因素）、affect（影响）、perfect（做完做透 → 完美的）。',
    words: [
      {
        name: 'factory',
        phonetic: '/ˈfæktri/',
        breakdown: 'fact (做/造) + -ory (场所)',
        meaning: 'n. 工厂；制造厂',
        example: {
          en: 'The automobile factory produces hundreds of electric vehicles daily.',
          cn: '这家汽车工厂每天生产数百辆电动汽车。',
        },
      },
      {
        name: 'factor',
        phonetic: '/ˈfæktər/',
        breakdown: 'fact (做) + -or (起作用之物)',
        meaning: 'n. 因素；要素；因子',
        example: {
          en: 'Consistent daily effort is a key factor in language learning.',
          cn: '持之以恒的日常努力是语言学习的关键成功因素。',
        },
      },
      {
        name: 'affect',
        phonetic: '/əˈfekt/',
        breakdown: 'ad- (对...) + fect (作用/做)',
        meaning: 'v. 影响；感染；感动',
        example: {
          en: 'Global climate changes directly affect agricultural yields.',
          cn: '全球气候变化直接影响着各地的农业收成。',
        },
      },
      {
        name: 'perfect',
        phonetic: '/ˈpɜːrfɪkt/',
        breakdown: 'per- (完全) + fect (做成)',
        meaning: 'adj. 完美的；极好的 v. 使完美',
        example: {
          en: 'Practice makes perfect in mastering any complex skill.',
          cn: '熟能生巧是掌握任何复杂技能的不二法则。',
        },
      },
      {
        name: 'defect',
        phonetic: '/ˈdiːfekt/',
        breakdown: 'de- (欠缺/脱离) + fect (做)',
        meaning: 'n. 缺点；瑕疵；缺陷',
        example: {
          en: 'Quality inspection ensures products have no structural defects.',
          cn: '严苛的质检确保产品没有任何结构性缺陷。',
        },
      },
    ],
  },
  {
    id: 'root_cap',
    form: 'cap / capt / cept',
    phonetic: '/kæpt/',
    meaning: '抓 / 拿 / 领会 / 容纳',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 capere / captus（抓取、握住、捕获）。引申至心智层面的“捕捉领会信息”与物理层面的“容器容量”。',
    derivationNote: 'capture（捕获）、accept（接纳抓住）、capacity（容纳力）、concept（一起抓住的想法 → 概念）。',
    words: [
      {
        name: 'capture',
        phonetic: '/ˈkæptʃər/',
        breakdown: 'capt (抓) + -ure',
        meaning: 'v. 捕获；俘获；捕捉',
        example: {
          en: 'The photographer managed to capture the rare bird in flight.',
          cn: '摄影师成功抓拍到了这种珍稀鸟类飞翔的瞬间。',
        },
      },
      {
        name: 'accept',
        phonetic: '/əkˈsept/',
        breakdown: 'ad- (向着) + cept (拿/取)',
        meaning: 'v. 接受；承认；同意',
        example: {
          en: 'She gladly accepted the prestigious scholarship award.',
          cn: '她欣然接受了这项极具声望的奖学金荣誉。',
        },
      },
      {
        name: 'concept',
        phonetic: '/ˈkɑːnsept/',
        breakdown: 'con- (共同) + cept (脑海里抓住的想法)',
        meaning: 'n. 概念；观念；思想',
        example: {
          en: 'The new concept car showcases futuristic green technologies.',
          cn: '这台全新的概念车展示了面向未来的前沿绿色科技。',
        },
      },
      {
        name: 'capacity',
        phonetic: '/kəˈpæsəti/',
        breakdown: 'cap (容纳/拿) + -acity',
        meaning: 'n. 容量；能力；生产力',
        example: {
          en: 'The auditorium has a maximum seating capacity of two thousand.',
          cn: '该礼堂的最大座位容纳量为两千人。',
        },
      },
      {
        name: 'intercept',
        phonetic: '/ˌɪntərˈsept/',
        breakdown: 'inter- (在中间) + cept (抓取)',
        meaning: 'v. 拦截；截获；阻截',
        example: {
          en: 'The security firewall intercepted unauthorized network requests.',
          cn: '安全防火墙成功拦截了未经授权的恶意网络请求。',
        },
      },
    ],
  },
  {
    id: 'root_gen',
    form: 'gen / gener',
    phonetic: '/dʒen/',
    meaning: '生 / 出生 / 产生 / 种类',
    category: 'latin',
    categoryLabel: '希腊&拉丁经典词根',
    origin: '源自希腊语与拉丁语 genos / genus（出生、繁殖、生成）。是生物基因学、发电能源与时代世代的核心构词根。',
    derivationNote: 'generate（产生/发电）、generation（一代人）、genius（天生天才）、general（普遍总体的）。',
    words: [
      {
        name: 'generate',
        phonetic: '/ˈdʒenəreɪt/',
        breakdown: 'gen (产生) + -er + -ate',
        meaning: 'v. 产生；生成；发电',
        example: {
          en: 'Wind turbines generate clean renewable electricity for the city.',
          cn: '风力发电机为城市源源不断产生洁净的可再生电能。',
        },
      },
      {
        name: 'generation',
        phonetic: '/ˌdʒenəˈreɪʃn/',
        breakdown: 'gener (繁殖) + -ation',
        meaning: 'n. 一代人；代际；产生',
        example: {
          en: 'The younger generation embraces rapid digital transformation.',
          cn: '年轻一代热忱拥抱快速演进的数字化变革。',
        },
      },
      {
        name: 'genius',
        phonetic: '/ˈdʒiːniəs/',
        breakdown: 'gen (生来具备的天赋) + -ius',
        meaning: 'n. 天才；天赋；才华',
        example: {
          en: 'Albert Einstein is widely recognized as a scientific genius.',
          cn: '阿尔伯特·爱因斯坦被公认为伟大的科学天才。',
        },
      },
      {
        name: 'general',
        phonetic: '/ˈdʒenrəl/',
        breakdown: 'gener (种类) + -al (同属一类的)',
        meaning: 'adj. 普遍的；大体的 n. 将军',
        example: {
          en: 'There is general agreement on the core project milestones.',
          cn: '大家对核心的项目里程碑达成了普遍一致的共识。',
        },
      },
      {
        name: 'genuine',
        phonetic: '/ˈdʒenjuɪn/',
        breakdown: 'gen (生来天然的) + -uine',
        meaning: 'adj. 真实的；真诚的；非人造的',
        example: {
          en: 'Her genuine enthusiasm inspired the entire research group.',
          cn: '她发自内心的真挚热情感染了整个科研小组。',
        },
      },
    ],
  },
  {
    id: 'root_vert',
    form: 'vert / vers',
    phonetic: '/vɜːrt/',
    meaning: '转 / 转向 / 改变',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 vertere / versus（旋转、掉头、改变方向）。引申至思维转变、事物多样性与逆境克服。',
    derivationNote: 're-（转回去 → 恢复）、di-（转向不同方向 → 丰富多元）、ad-（把视线转过来 → 广告）。',
    words: [
      {
        name: 'convert',
        phonetic: '/kənˈvɜːrt/',
        breakdown: 'con- (完全) + vert (转)',
        meaning: 'v. 转变；转换；皈依',
        example: {
          en: 'Solar panels convert sunlight directly into usable power.',
          cn: '太阳能电池板将阳光直接转换为可利用的电力。',
        },
      },
      {
        name: 'diverse',
        phonetic: '/daɪˈvɜːrs/',
        breakdown: 'di- (向各个方向) + vers (转)',
        meaning: 'adj. 多元化的；多样的；形形色色的',
        example: {
          en: 'The metropolis boasts a rich and diverse culinary culture.',
          cn: '这座大都市拥有丰富且多元的美食文化。',
        },
      },
      {
        name: 'reverse',
        phonetic: '/rɪˈvɜːrs/',
        breakdown: 're- (往回) + vers (转)',
        meaning: 'v. 倒转；颠倒；倒车 adj. 反向的',
        example: {
          en: 'The court decided to reverse the previous legal ruling.',
          cn: '法院决定推翻撤销先前的法律裁决。',
        },
      },
      {
        name: 'advertise',
        phonetic: '/ˈædvərtaɪz/',
        breakdown: 'ad- (向着) + vert (吸引转向) + -ise',
        meaning: 'v. 做广告；宣传；公布',
        example: {
          en: 'Companies advertise their novel products across social media.',
          cn: '各大公司在社交媒体平台上大力宣传其创新产品。',
        },
      },
      {
        name: 'adverse',
        phonetic: '/ædˈvɜːrs/',
        breakdown: 'ad- (对着) + vers (转过来面对的阻力)',
        meaning: 'adj. 不利的；逆向的；有害的',
        example: {
          en: 'The brave expedition continued despite adverse weather conditions.',
          cn: '尽管面临不利的恶劣天气，勇敢的探险队依然继续前进。',
        },
      },
    ],
  },
  {
    id: 'root_scrib',
    form: 'scrib / script',
    phonetic: '/skrɪpt/',
    meaning: '写 / 描画 / 记录',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 scribere / scriptus（书写、刻写、记录）。是现代出版、软件脚本与医学处方的共同源头。',
    derivationNote: 'de-（描摹写下 → 描述）、sub-（在下方签名 → 订阅）、pre-（预先写好药单 → 开处方）。',
    words: [
      {
        name: 'describe',
        phonetic: '/dɪˈskraɪb/',
        breakdown: 'de- (向下/详细) + scrib (写)',
        meaning: 'v. 描述；描写；形容',
        example: {
          en: 'The eyewitness described the suspect in great detail.',
          cn: '目击者极其详尽地描述了嫌疑人的体貌特征。',
        },
      },
      {
        name: 'subscribe',
        phonetic: '/səbˈskraɪb/',
        breakdown: 'sub- (在底端) + scrib (签字/写下)',
        meaning: 'v. 订阅；赞同；定期捐助',
        example: {
          en: 'Millions of users subscribe to the streaming channel.',
          cn: '数百万用户订阅了该知名流媒体频道。',
        },
      },
      {
        name: 'prescribe',
        phonetic: '/prɪˈskraɪb/',
        breakdown: 'pre- (事先) + scrib (写下药方)',
        meaning: 'v. 开处方；规定；开药',
        example: {
          en: 'The doctor prescribed mild antibiotics for the infection.',
          cn: '医生针对感染开具了温和的抗生素处方。',
        },
      },
      {
        name: 'manuscript',
        phonetic: '/ˈmænjuskrɪpt/',
        breakdown: 'manu- (手) + script (写)',
        meaning: 'n. 手稿；原稿；底稿',
        example: {
          en: 'The author submitted the final novel manuscript to the publisher.',
          cn: '作者向出版商正式递交了小说最终手稿。',
        },
      },
      {
        name: 'script',
        phonetic: '/skrɪpt/',
        breakdown: 'script (书写之文)',
        meaning: 'n. 剧本；脚本；笔迹 v. 编剧',
        example: {
          en: 'The developer wrote an automated Python script to backup databases.',
          cn: '开发者编写了一个自动化 Python 脚本来定期备份数据库。',
        },
      },
    ],
  },
  {
    id: 'root_ced',
    form: 'ced / ceed / cess',
    phonetic: '/siːd/',
    meaning: '走 / 步入 / 让步',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 cedere / cessus（行走、前进、撤退、让步）。广泛构建了进程、成功与访问权等核心动词网络。',
    derivationNote: 'pro-（向前走 → 进行）、suc-（在后面跟着走上来 → 成功/继任）、ac-（走近接触 → 访问）。',
    words: [
      {
        name: 'proceed',
        phonetic: '/proʊˈsiːd/',
        breakdown: 'pro- (向前) + ceed (走)',
        meaning: 'v. 继续进行；前进；起诉',
        example: {
          en: 'The flight will proceed as scheduled without delays.',
          cn: '航班将按预定计划正常起飞，不会延误。',
        },
      },
      {
        name: 'succeed',
        phonetic: '/səkˈsiːd/',
        breakdown: 'sub- (在后面) + ceed (接着走上来)',
        meaning: 'v. 成功；继任；继承',
        example: {
          en: 'With relentless dedication, she succeeded in launching her startup.',
          cn: '凭借不懈的专注与付出，她成功创立了自己的企业。',
        },
      },
      {
        name: 'access',
        phonetic: '/ˈækses/',
        breakdown: 'ad- (向着) + cess (走近/进入)',
        meaning: 'n. 入口；访问权 v. 访问；存取',
        example: {
          en: 'All verified employees have 24/7 access to the laboratory.',
          cn: '所有认证员工均享有全天候进出实验室的通行权限。',
        },
      },
      {
        name: 'process',
        phonetic: '/ˈprɑːses/',
        breakdown: 'pro- (向前) + cess (走出来的步骤)',
        meaning: 'n. 过程；工序 v. 处理；加工',
        example: {
          en: 'Application processing typically takes three business days.',
          cn: '申请审核流程通常需要三个工作日。',
        },
      },
      {
        name: 'recede',
        phonetic: '/rɪˈsiːd/',
        breakdown: 're- (向后) + ced (走/退)',
        meaning: 'v. 后退；减弱；渐渐远离',
        example: {
          en: 'Floodwaters began to recede after the storm passed.',
          cn: '暴风雨过去后，洪水水位相继开始消退。',
        },
      },
    ],
  },
  {
    id: 'root_duc',
    form: 'duc / duct',
    phonetic: '/dʌkt/',
    meaning: '引导 / 带领 / 产生',
    category: 'latin',
    categoryLabel: '拉丁核心词根',
    origin: '源自拉丁语 ducere / ductus（引领、引导、带来）。从教育孩子（educate）到工业生产（produce）无所不包。',
    derivationNote: 'intro-（领进来 → 介绍）、pro-（向前带出来 → 生产）、re-（往回带减少 → 降低）。',
    words: [
      {
        name: 'produce',
        phonetic: '/prəˈduːs/',
        breakdown: 'pro- (向前) + duc (引导/产生)',
        meaning: 'v. 生产；制造；引起 n. 农产品',
        example: {
          en: 'Organic farms produce pesticide-free fresh vegetables.',
          cn: '有机农场生产无农药残留的新鲜蔬菜。',
        },
      },
      {
        name: 'educate',
        phonetic: '/ˈedʒukeɪt/',
        breakdown: 'e- (向外引申) + duc (带) + -ate',
        meaning: 'v. 教育；培养；教导',
        example: {
          en: 'Schools aim to educate students into responsible global citizens.',
          cn: '学校旨在将学生培养为具有责任感的地球公民。',
        },
      },
      {
        name: 'introduce',
        phonetic: '/ˌɪntrəˈduːs/',
        breakdown: 'intro- (向内) + duc (领)',
        meaning: 'v. 介绍；引进；提出',
        example: {
          en: 'The tech giant introduced an innovative flagship smartphone.',
          cn: '这家科技巨头推出了一款极具突破性的旗舰智能手机。',
        },
      },
      {
        name: 'reduce',
        phonetic: '/rɪˈduːs/',
        breakdown: 're- (往回/向下) + duc (带)',
        meaning: 'v. 减少；降低；缩小',
        example: {
          en: 'Digital workflows dramatically reduce paper waste.',
          cn: '数字化工作流显著减少了纸质文档的浪费。',
        },
      },
      {
        name: 'conduct',
        phonetic: '/kənˈdʌkt/',
        breakdown: 'con- (共同) + duct (带领/指导)',
        meaning: 'v. 实施；引导；指挥 n. 行为',
        example: {
          en: 'The research institute will conduct nationwide clinical trials.',
          cn: '该研究所将在全国范围内开展临床试验。',
        },
      },
    ],
  },
]
